### ISSUE TITLE
Input.GetKeyWithBinding( string ) should be Input.GetKeyWithBinding( InputButton )

### ISSUE THREAD

**Issue by handsomematt** [Facepunch/sbox-issues#1014]
**What it is**

```csharp
Input.GetKeyWithBinding( "iv_drop" )
```

I have to know that InputButton.Drop is the equivalent of "iv_drop".

**What it should be**

```csharp
Input.GetKeyWithBinding( InputButton.Drop )
```

---

Additionally a way to do the same for gamepad buttons should be added.

**Comment by Alf21** [comment]
Isn't the intention of this function to get the Key (`InputButton` as a return) that is connected with the provided binding command? So imo, wouldn't make sense to provide an InputButton in order to receive an InputButton...

**Comment by handsomematt** [comment]
It returns what the InputButton is bound to by the user, e.g

`Input.GetKeyWithBinding( "+iv_score" )` returns "TAB" by default.

It is for telling the user what button to press for an action.

**Comment by Alf21** [comment]
Yea. And if I'm doing something custom like `Input.GetKeyWithBinding("+ttt_chat")`, then the InputButton suggestion doesn't help a lot, better said, would break the current possibilities.

**Comment by Alf21** [comment]
It's an own teamchat. In TTT, you have to be able talking in a global chat and in a team chat. The binding key is for the latter one, and the player can decide which key he wanna use. It's a gamemode designed for PC-players (not console, etc.) as we as gamedevs just wanna support it atm. As a result, that would break a core mechanic, not just in that game.

Don't wanna discuss this in more details, just saying: It's needed in my case.

**Comment by handsomematt** [comment]
I don't think you understand the input system very well, your logic seems to depend on the fact that your game is doing

```csharp
ConsoleSystem.Run($"bind {BoundKey} {BoundCommand}");
```

Which doesn't work and shouldn't work. Just use the standard InputButton.* keys.

**Comment by Alf21** [comment]
I suggest using Git Blame in order to make claims - the code is 2 month old... Anyways, doesn't change my position:

If garry decides against custom key bindings, it's a set thing that would interfere with keyboard focussed games or fast-accessible quick-events in games (like we discussed). I thought, that's why you can tag your gamemode with controller, vr or keyboard support / focus.

Imo, custom key bindings are a feature. Restricting it is bad. If a game's UX is bad, make a better one or don't play it. It's a thing of the developer. You can still blame people if you want to :D

**Comment by xrayhunter-git** [comment]
@Alf21 
> Imo, custom key bindings are a feature. Restricting it is bad. If a game's UX is bad, make a better one or don't play it. It's a thing of the developer. You can still blame people if you want to :D

Agreed, I created a discussion about this earlier this year, talking about how others and I would like to see it implemented into the S&Box. https://github.com/Facepunch/sbox-issues/discussions/420

I believe if a gamemode developer chooses to make a million button combos and bindings, that is their own design choice. It's also their responsibility to notify the user of what those buttons mean.

Now, I do not believe as a gamemode developer that you should be able to **override** bindings from the base game, such as Forward, Backwards, Left, Right, Jump, and etc. **But!** This also entirely the gamemode developer's choice to use the default inputs given to them, which should be considered best-practice to use the confined inputs for day-to-day gameplay.

**Comment by xrayhunter-git** [comment]
https://github.com/Facepunch/sbox-issues/issues/1016
https://github.com/Facepunch/sbox-issues/issues/196

**Comment by Rohansi** [comment]
@Alf21 @xrayhunter-git It'd be more productive to continue that discussion in #420. This issue is about something else entirely.

"My gamemode my design choice" as an argument doesn't hold up too well because we (Facepunch) want gamemodes to be as accessible as possible no matter what input method players are using. Think about possible solutions that maintain both goals: custom input bindings which also allow controllers etc to map to them. Think about how binding could be done better, etc...

**Comment by handsomematt** [comment]
Added as `Input.GetButtonOrigin( InputButton button, bool ignoreController = false )`, Input.GetKeyWithBinding( string ) remains, but I'd recommend switching over:

```csharp
Input.GetKeyWithBinding( "iv_jump" )
Input.GetButtonOrigin( InputButton.Jump )
```
