### ISSUE TITLE
Whitelist System.Tuple

### ISSUE THREAD

**Issue by DaddyFrosty** [Facepunch/sbox-issues#125]
**What can't you do?**
Use System.Tuple

**How would you like it to work?**
Ability to use System.Tuple

**What have you tried?**
`List<Tuple<Point, Point>> sockets = new();`

**Additional context**
http://share.willswebsite.net/sbox-dev_CsaP6g7B6i.png

**Comment by TheBerkin** [comment]
While I agree `System.Tuple` should be whitelisted... I don't agree with your use case. Why not use [`System.ValueTuple`](https://docs.microsoft.com/en-us/dotnet/api/system.valuetuple?view=net-5.0), which C# 7 and later has built-in syntactic sugar for? Unless you need reference-sharing of those list elements, this makes a bunch of pointless heap allocations.

Instead of this:
```cs
List<Tuple<Point, Point>>
```
... you can do this:
```cs
List<(Point, Point)> // uses ValueTuple internally
```

`ValueTuple` is a struct, which is stack-allocated and reduces GC workload.

**Comment by DaddyFrosty** [comment]
Thought came from my C++ experience and `System.Tuple` was the first thing that popped up, but thanks for letting me know.

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3
