### ISSUE TITLE
Surfaces Don't have Bullet Holes

### ISSUE THREAD

**Issue by gvarados1** [Facepunch/sbox-issues#1288]
A lot of surfaces (concrete, dirt, ...) don't have any sounds or bullet holes/particles. This is because the surface asset type was updated to use an asset instead of a string for the Base Surface property. None of the surfaces were updated to reflect this change.
![image](https://user-images.githubusercontent.com/39461072/141717315-19ecd2b7-0dc4-4c98-b24f-488e24781752.png)

**Comment by garrynewman** [comment]
The Base property wasn't ever used, but yeah this is still a bug

**Comment by robotboy655** [comment]
Should be fixed. it will now inherit values from base surface if fields under "Sounds" and "Impact Effects" are blank.

Not really applicable for the "Physics" category with this system.

I had to add `Surface.GetBaseSurface()` (and complementary `Surface.SetBaseSurface()`) as I couldn't find a way for
```c#
public string BaseSurface { get; set; }
```
to work due to order of load issues where the base surface would load after a surface that inherits from it.

I also decided to not have each of the Surface properties return inherited values automagically as I feel the code would be a lot messier, especially since it is using structs.
