### ISSUE TITLE
Bug on Construct , passing through walls and glass!

### ISSUE THREAD

**Issue by TanyaDegurshaff** [Facepunch/sbox-issues#1383]
![20211209221047_1](https://user-images.githubusercontent.com/75164879/145445830-8969e27e-7507-48ad-9384-ffff865b2319.jpg)
On the Construct map there is a bug of passing through walls, this picture shows glass and a wall through which you can pass and fall through the map!!!

**Comment by robotboy655** [comment]
The bug is that transparent/translucent materials compile as non solid for some reason.

**Comment by PatrickJnr** [comment]
From what I noticed when checking in hammer is that the shutter does not extend all the way.

**Comment by DoctorGurke** [comment]
you don't think glass being non-solid is the issue?

**Comment by PatrickJnr** [comment]
It actually could be, yeah.

**Comment by Oppossome** [comment]
> The bug is that transparent/translucent materials compile as non solid for some reason.

The bug is no longer reproducible on construct, however you are able to test it in the following location of bakscratch's office map. 
![image](https://user-images.githubusercontent.com/15877760/153732581-c6040228-888c-41e8-8f71-de9911bd3497.png)

It appears to be solved by adding the CollisionLayer.STATIC_LEVEL to
- BasePlayerController.cs
![devenv_2022-02-12_18-51-37](https://user-images.githubusercontent.com/15877760/153732541-bf01a47b-8d0b-4bf7-bc17-5212dd2da929.png)
- MoveHelper.cs
![devenv_2022-02-12_18-38-27](https://user-images.githubusercontent.com/15877760/153732309-bcd95b83-ef57-42ac-a9ed-ff279ac6ec18.png)

Demonstration 
- Before
https://user-images.githubusercontent.com/15877760/153732747-f84a2da9-764e-4da0-bf0b-2a6009702d82.mp4
- After
https://user-images.githubusercontent.com/15877760/153732752-544b664c-98f9-4f1b-8df8-f9d20f5be0d7.mp4
