### ISSUE TITLE
Crash when resizing Hammer's Fast Texture Tool window

### ISSUE THREAD

**Issue by RobertPoncelet** [Facepunch/sbox-issues#1413]
When using the Fast Texture Tool in Hammer, it's possible to cause a crash by messing with the window size for a few seconds.

To reproduce:

1. Select a face in Hammer and open the Fast Texture Tool.
2. Resize the tool window to a large square so the material grid preview is as large as possible: 
![image](https://user-images.githubusercontent.com/8983298/145890913-73a7c2d6-59e3-4bd1-9335-76cf7f8417d6.png)
3. Resize the tool window to be very wide and short, making the grid preview as small as possible:
![image](https://user-images.githubusercontent.com/8983298/145891083-620ea9b0-8f63-4bd1-966f-5122c4ccb40c.png)
4. Repeat steps 2 and 3 a few times until a crash occurs.

(Incidentally, it'd be nice to be able to pan/zoom the grid preview so it's easier to set the UVs outside of the 0-1 space.)

I reproduced this on two machines: AMD/Intel, GTX 1060/1070, both Windows 10.

Here's a memory dump:
[sbox-dev_2021_1213_210912_0_accessviolation.zip](https://github.com/Facepunch/sbox-issues/files/7707043/sbox-dev_2021_1213_210912_0_accessviolation.zip)

**Comment by handsomematt** [comment]
This should be fixed in the next build, instead of crashing it'll just not allocate the render target if it runs out. ( It'll appear as an invalid texture and resizing the window again will fix it, this is probably fine since you shouldn't have this happen unless you are intentionally trying to break it now. )

I also doubled the max number of render targets so it should be a lot harder to run out even from repeatedly rapidly changing window size.

**Comment by RobertPoncelet** [comment]
Nice, it seems to be all good now. Thanks for the quick response 👍
