### ISSUE TITLE
Ability to include external dlls or nuget packages in addons.

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#166]
**What can't you do?**

Share code between a web api and an addon.

**How would you like it to work?**

A special folder inside your addon for dlls and nuget packages. They will be referenced by your project when you run `GenerateProjects` and loaded with your addon after it is compiled but still be checked by the whitelist.

**What have you tried?**

Copy pasting code but it isn't feasible.

**Additional context**

Although lots of dlls will use blacklisted methods, there is still utility in making a dll that follows the whitelist.

When loading the dll into the game it can be checked by the whitelist removing the issue of exploits.

**Comment by Erlite** [comment]
Yes please, server-side only is all we need. An idea would be to only enable third party DLLs if the game (for listen servers) or dedicated servers is started with `-unsafe` of something of the sort. Without this, the user/server would be met with an error message when loading an addon saying they use 3rd party DLLs and could potentially be unsafe.

We all know people are going to have a simple step of "replace `sbox/config/accessgroups/baseaccess.txt` with `myAddon/baseaccess.txt`" in their installation steps, with a fully permissive whitelist. `-unsafe` would just disable the whitelist completely and allow referencing other DLLs. This would only be on the server.

The other "solution/hack" is just someone making an addon that handles loading assemblies and resolving them due to how s&box dynamically compiles and loads them. It's messy and it'd likely work, except it'd just be a pain for developers to use instead of something natively supported by s&box.

**Comment by Jake-Rich** [comment]
We need client side too if we want to interact with a web api. To begin with I just want support for loading dlls as if they were part of your code. 

Having unrestricted code on the server involves a lot more complexity as you will have to strip out all the blacklisted code before sending it to the client, and is something I don't need yet.

**Comment by Erlite** [comment]
Ah yeah I didn't read that correctly, and also kind of got carried away. 

But yeah, it'd be nice to be able to reference DLLs so we don't have to rewrite code.

**Comment by thisisomar** [comment]
Just to understand correctly, are you saying to allow nuget packages but only packages that are fully permissive in terms of the whitelist?

When it comes to the access list, yeah it's that easy right now, but I'm sure in the future, they could verify the list against some sort of "backend" or something, sort of like an anti cheat to prevent people from ever modifying it. 

Not sure how Garry feels about this, but it definitely would be nice, I know he already voiced his concern about this, but I don't know if he'd feel any different about this approach I guess

**Comment by Jake-Rich** [comment]
Yes to begin with only allowing packages that fully comply with the whitelist. 

I understand his concern against downloading nuget packages as a means of distribution. Instead the package(s) would be bundled with your addon and could be referenced by the csproj directly, same deal with dlls outside of packages.

**Comment by thisisomar** [comment]
Ah I see, thanks for clarifying, definitely would love to see this be possible as a lot of nuget packages are quite helpful.

As Erlite said, people are just going to rewrite with what they have access to or try to, but honestly, it's a lot better to figure out a way to give access.
