### ISSUE TITLE
Weapons don't show after dropping them anymore

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#1685]
**To Reproduce**

1. Open Sandbox game mode
2. Drop the pistol
3. Notice that the pistol doesn't show up

**Expected behavior**

The pistol should show up.

**Additional context**

Probably related to this fix that occured https://github.com/Facepunch/sbox-issues/issues/1655 also occurring in other gamemodes. I'm assuming a knock-on change.

**Comment by aylaylay** [comment]
fuck sake

**Comment by NotGaylien** [comment]
with that change (now reverted)
basically anything added to your inventory but NOT set to makeactive in the inventory.Add( ent ) wont show up when dropped.
however if it IS set to true and forces you to have it in hand, then it will. inventory.Add( ent, true ); 
so the issue is related to when it gets added and then you switch to it manually, it wont show up, which is strange.

**Comment by mzegar** [comment]
thanks
