### ISSUE TITLE
Gamemodes should be able to read the key bind configs

### ISSUE THREAD

**Issue by MasterMann** [Facepunch/sbox-issues#172]
**What can't you do?**
Read input bind keys (i.e. "E", ""Space", etc.), for example to display stuff like "press <X> to interact", replacing X with the bound key for use.

**How would you like it to work?**
```csharp
string keyName = Local.Input.GetKeyForAction(InputActionType.Use).KeyName;
bool isBindingSet = Local.Input.IsActionBoundToKey(InputActionType.Use);

InputAction[] actions = Local.Input.Actions;
string keyName = Local.Input.Actions[InputActionType.Use].KeyName;
bool isBindingSet = Local.Input.Actions[InputActionType.Use].IsBound;
```

**What have you tried?**
N/A.

**Additional context**
None.

**Comment by Alf21** [comment]
As we have `Sandbox.Input.GetKeyWithBinding(string binding)`, it would be great to have `Sandbox.Input.GetBindingWithKey(string key)` as well :)

**Comment by garrynewman** [comment]
Isn't *Sandbox.Input.GetKeyWithBinding* what you want here?

**Comment by Alf21** [comment]
No: `GetKeyWithBinding` returns the key (string) of the provided binding / console command.

I want to get the commands / console commands that are currently bound to a provided key (string), like

`GetBindingWithKey("space")` -> `iv_jump`.

Why: I don't want to force players to use bindings nor to override already bound keys. That's why I need to access the bindings. As well as to provide the player an overview about what is bound to what key.
