### ISSUE TITLE
Editor: Assets browser settings aren't persistent

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#1860]
### Describe the bug

When you change any of the settings in the assets browser (like the view mode), they don't persist between game restarts or when the tab becomes a floating window

### To Reproduce

1. Open the s&box editor, go to the assets browser
2. Click the settings cog next to the file path text entry
3. Switch from list view to large icons
4. Restart the game or drag the tab out so that it becomes a window
5. The asset browser will switch to list view again

### Expected behavior

The assets browser should retain any settings that the user changes

**Comment by garrynewman** [comment]
Should be fixed now

**Comment by xezno** [comment]
Yep, works nicely now. Thank you!

**Comment by NotGaylien** [comment]
Can i just make 1 tiny request.

In the Browsers tool addon AssetBrowser.cs.

can the settings from the cookie be loaded before data set is updated.
like so
![image](https://user-images.githubusercontent.com/82092361/170561729-ae26b80f-1597-47be-a7f7-1bd36e2e07d9.png)
![image](https://user-images.githubusercontent.com/82092361/170561845-8b354de8-51f3-47d4-9229-bb2b231a6753.png)


Since atm them settings are retrieved after everything visually has already happened. (it works once you click any folder ofc though)
Calling it before gets them loaded in fine and settings are there on first boot for recursive files & junk files.
<3
