### ISSUE TITLE
Panels have unsigned values

### ISSUE THREAD

**Issue by Wall3rHM2** [Facepunch/sbox-issues#1937]
### Describe the bug

The Panel class with the Yoga Layout returns 0 in all values that should describe the size of the panel object, such as all Rect attributes, and when you try to use Style.Height.Value.HasValue returns false, thus the value is not even set. This only changes when you override the FinalLayout function, that gets the correct values.

### To Reproduce

1. Create any panel object (Labels, Panels, TextEntry, and so on...)
2. Call any property regarding the size of the panel object (such as Panel.Box.Left, Panel.Style.Height.Value.Value, and so on...)
3. Now you get only the 0 value or your game breaks

### Expected behavior

Return the correct values. Since the Yoga layout also dont support multi line at the same time with multiple texts objects being used in the same paragraph, this makes it impossible to create any complex text coloring, such as a custom chat with multiple colors inside the text and text wrapping, or a code editor inside the game.

### Media/Files

![image](https://user-images.githubusercontent.com/38440423/173904289-6485c3ac-7b88-4056-8716-f655e0495681.png)

### Additional context

The minimum that is expected is a option to disable Yoga Layout so it does not interfere or break my code. Using absolute position also does not fix this problem, the returned height/width is still wrong.

**Comment by DoctorGurke** [comment]
Try ComputedStyle instead of Style to *get* the style without manually setting it

**Comment by Adesii** [comment]
oh right.. i missed like the one line you mentioned it in..
if you want complex text coloring just render it yourself using Render.Draw2D instead of just using panels.

And also the examples that you gave with multiple text coloring in the same text etc. are definitely possible with flexbox.
And for a Code Editor you probably wouldn't want to use panels for that anyway.

If you gave a example ZIP where it clearly shows the issue. It would be more easy to fix (assuming there is a reason to fix it)

**Comment by Wall3rHM2** [comment]
![image](https://user-images.githubusercontent.com/38440423/173958232-939f11c4-fd0c-4023-b0fa-e05235858bb8.png)
this is what happens when you try to make it work (using background-color so its easier to notice the draw area of each label)
![image](https://user-images.githubusercontent.com/38440423/173958344-2188042b-d23f-44ed-8991-63b7cf5dade1.png)
I didn't find anything at all about Render.Draw2D in any of sbox .cs files. Will be uploading a ZIP file later on.

**Comment by Wall3rHM2** [comment]
Here is the zip for testing
[issue.zip](https://github.com/Facepunch/sbox-issues/files/8920066/issue.zip)

**Comment by Adesii** [comment]
> Here is the zip for testing [issue.zip](https://github.com/Facepunch/sbox-issues/files/8920066/issue.zip)

Use Templates... makes debugging UI elements 100x easier and faster ontop of just more organized.
You are also trying to get the Box of a Panel before the first Layout. That makes no sense. if the Panel hasn't been laid out yet how would you get its final width/height etc. from it.

Just put PrintValues into Tick and see it working like expected. any logic you want to do on the panel like restrict size should also be done inside TIck or OnLayout not on Panel Creation since values can always change.

here is my Zip. if you want to see how i would do things:
[bug_report.zip](https://github.com/Facepunch/sbox-issues/files/8922709/bug_report.zip)

Also the Example above with the Text wrapping and such has nothing to do with the Getting size and such.
That is definitely something you'll implement with your own Panel Type and using Render.Draw2D (you can find examples, in the DM gamemode or just use Intellisense since it isn't actually complicated)

**Comment by cr4yz** [comment]
Regarding the flashing ui you might want to set the opacity to zero before the panel is created.  For empty layout data, the layout override methods are there to let you know when layouts are calculated and ready, it will not exist yet in the constructor.
