### ISSUE TITLE
Improve inspector asset preview window

### ISSUE THREAD

**Issue by DoctorGurke** [Facepunch/sbox-issues#2049]
### For?

S&Box, Other

### What can't you do?

The new asset inspector preview offers extremely little information about the inspected asset. At this time it only has a pivot and zoom for models, for example. 
![sbox-dev_efVQdBe145](https://user-images.githubusercontent.com/12602100/180432645-3fe04486-157d-432f-9a54-2cf81d4f2720.png)

Debug features such as wireframe, skeleton, lighting previews, toolsvis modes, animation preview, material group selector, hitboxes, mesh info (mesh count. draw calls, polys) and many more are completely missing. Being able to quickly see which models support prop physics (hulls), static physics (mesh) or none would also be an excellent feature that even the legacy browser doesn't easily show.
![sbox-dev_aV4DPncuuK](https://user-images.githubusercontent.com/12602100/180433003-8fca380e-25c2-46df-9db7-4ee0e44e4e81.png)

On the topic of toolsvis modes, the editor selector doesn't seem to apply to this panel, whereas the LOD selector works fine, which is why I didn't mention that.

I would agree that it's possible to improve the legacy asset browser ui for all of these, but as it stands now, the new preview window gives you extremely little information.

### How would you like it to work?

Even on small inspector sizes there seems to be a substancial amount of deadspace right now.
![sbox-dev_SC9VmUuNQj](https://user-images.githubusercontent.com/12602100/180433290-6f5b647e-ad2e-41b7-9b54-a08792834659.png)
I believe the preview could be integrated better into the inspector as it stands right now, providing the freedom of rethinking most of these debug options and their place on the ui.

### What have you tried?

Currently the preview only allows for a basic pivot around the center point of the model and a zoom.

### Additional context

The legacy assetbrowser preview has a lot of hidden features that many people probably don't even know about, like being able to rotate the preview lightrig by holding L and moving the mouse with leftclick held down. It would be lovely if some of these more niche but incredibly helpful features would be more streamlined via better/more intuitive controls or ui elements.

**Comment by DoctorGurke** [comment]
It would also be nice to mention that an optional preview grid in this window for a sense of scale would be incredible. I know it's not desirable for that grid to show up on the thumbnails, but if we could at least get it for the preview window that'd be lovely

**Comment by NotGaylien** [comment]
(sorry for bump)
But this is a really big thing for me, mainly these
https://i.imgur.com/ppYB9Nu.png

i cant describe how useful it is to change the environment lighting and tools vis modes.
it helps a fuck ton to find issues with things like issues in your material, without having to open up multiple in game maps to test the model in different lighting conditions to see if its working fine or not ingame, since coming from other software it can look somewhat different.

and also it can be really useful to quickly look at each individual texture map since you can have weird issues and it turns out to be something messed up on your roughness map thats making things look wonky.
some could argue that isnt important to be in sbox, but it really does speed working with models and finding issues up so quick.

Also quickly finding animation sequence name or material group using the main big options are also really useful when doing stuff, it can save alot of time having to have a model open to see them when you can quickly access them from the models inspector preview, and then know exactly which to use in your game, idk if coders use that but as someone who messes on both sides of art / code i really do use that alot.

**Comment by DoctorGurke** [comment]
The current preview is essentially useless, quite frankly

**Comment by garrynewman** [comment]
Debug views I don't know about. It seems like this isn't the place for it. Like shouldn't you double click to view this stuff?

Envmap etc definitely.

**Comment by DoctorGurke** [comment]
double click as in open it in the editor? the inspector preview is invaluable because we don't need to open a new editor window/tab for every asset we want to look at. We just click the specific asset once and immediately see the preview update. Being able to quickly compare assets, including some debug/technical data is very useful and has proven useful with the old asset browser imho

**Comment by garrynewman** [comment]
You can't quickly compare assets though because one disappears when you click on the other. I really don't think the tiny asset preview window is the place for this stuff.

**Comment by DoctorGurke** [comment]
I see what you mean, maybe something else can be done with the dockable widgets that doesn't rely on opening the dedicated editor for the assets?

**Comment by NotGaylien** [comment]
opening them one by one ends up with a bunch of modeldoc windows though. and that just becomes a pain if you want to keep going back and fourth between the windows to check shit.
(not to mention there is good second delay waiting for stuff to open, longer on some models quicker on some.)

i mean its not the end of the world losing that since i mainly use it while trouble shooting issues or just admiring other peoples models and textures. 

---
BUT!!! i do think its realllllllllly useful to have something on the model inspector that gives you a way to see all the **material groups**  **body groups** and maybe even **animation sequences** and to view them, so you know what they look like and are called.

since i feel like there would be a good chunk of coders who want to grab a model and it would be a really nice quick easy place to see what there is to mess with on said model.

**Comment by DoctorGurke** [comment]
pretty please?

https://user-images.githubusercontent.com/12602100/221620156-dd2f7e9b-9b0d-4670-9290-508f2f28eefc.mp4
