### ISSUE TITLE
VMF Importing -  Texture Scale Bug

### ISSUE THREAD

**Issue by Hichatu** [Facepunch/sbox-issues#2098]
### Describe the bug

When importing a Source1 .vmf, every texture scale is seemingly divided by a power of 2 (128, 64, 32, etc.) depending on the original texture resolution.

Importing existing Source1 maps is a massive task already, but this texture scale issue just amplifies the problem, would be great if it could be fixed for easier porting.

Texture X/Y shift values also seem to be affected when importing the .vmf.

### To Reproduce

Launch Hammer
Open -> Switch to Source1 VMF
Open and load .vmf file
Check the texture x and y scale, compared to Source1 Hammer, it will have been divided by a power of 2.

### Expected behavior

The x and y scale values should be the same across Source1 and Source2. Perhaps it is a brush -> mesh conversion bug?

### Media/Files

Source 1 selected face, and X/Y scale values
![image](https://user-images.githubusercontent.com/47224085/182064624-48d17a98-3235-4944-bc49-ad80749f2815.png)

Source2 / s&box selected face, and X/Y scale values
![image](https://user-images.githubusercontent.com/47224085/182064790-0f0f6823-375f-4a6d-9974-bc5df0c1a6af.png)

### Additional context

This is also a bug within HL:A's Hammer Editor.

**Comment by Redhacker1** [comment]
This was previously closed by Layla as won't fix, I don't see why making this issue again is going to change that, in fact Layla contemplating removing the vmf importer entirely

**Comment by Redhacker1** [comment]
For the record it's  (size of the texture) / 16 *  uvscale to fix it

**Comment by DoctorGurke** [comment]
As redhacker sort of hinted at, the issue here is that vmf doesn't store face uv's, but rather how textures are transformed on said face/plane, based on the original texture size. So for the importer to work, it'd need access to the materials/textures in question. I think it is/used to be possible to manipulate your local game info to provide said files, but it's really shit and doesn't sound like something that should be a default feature in sbox.
For the record, bsp also stores face uv's this way, but it compiles the texture sizes into its texture lump, so it doesn't need any other info/files to render everything properly
