### ISSUE TITLE
Animgraph, messed up face

### ISSUE THREAD

**Issue by CrezyDud** [Facepunch/sbox-issues#2166]
### Describe the bug

face gets ruined, always different (sometimes face stays normal)
![grafik](https://user-images.githubusercontent.com/84625713/184421579-237b089b-b193-47d8-ab92-20b2922380ac.png)
But it's totally fine in Model Doc
![grafik](https://user-images.githubusercontent.com/84625713/184421621-c5598eec-1985-4f75-aa53-1b394afd7614.png)

### To Reproduce

When i add a simple animation to animgraph, connect it directly to Final Pos
and click test, it happens..
![grafik](https://user-images.githubusercontent.com/84625713/184421845-c01534ca-1056-430e-bcff-76956f95b7f8.png)

as said, fine in model doc

### Expected behavior

face.. normal.. please..

### Media/Files

[punch.txt](https://github.com/Facepunch/sbox-issues/files/9329163/punch.txt)
(is .fbx, but github)
[punch2.txt](https://github.com/Facepunch/sbox-issues/files/9329190/punch2.txt)
(is .blend)

### Additional context

Arch Linux, Proton Experimentell

it may be the animation itself
i have no idea, i havent seen anything in the wiki describing how to export a simple animation properly
and i didnt configure the fbx (except only exporting skeleton), but as said, it looks fine in model doc

**Comment by aylaylay** [comment]
Check if it's broken on windows

**Comment by CrezyDud** [comment]
vanilla animations work fine, not a linux problem, it's somehow making my animation broken,
but model doc has it fine, so it's a bug

**Comment by aylaylay** [comment]
Show me a screenshot of it broken in windows. It's fine here.

**Comment by LazyDuchess** [comment]
I had this issue as well, and I believe it only happens when using animations that have no morph keyframes with animgraph, both in the preview and in-game (Such as custom animations exported as FBX)

Can reproduce it by importing any of the included source FBX animations with citizen.vmdl as the base model and creating an empty animgraph with just the added animation connected to the final pose.

It looks like garbage data is sent to the renderer instead of morph values, causing the issue.

To workaround this you can use an Only_Morphs bone mask to take the morphs from another animation that does have keyframes for them (using bindpose in this example for a neutral face):
![image](https://user-images.githubusercontent.com/42678262/184479706-8de29191-8ae2-4d1f-94e0-be2307d7c491.png)

I use Windows myself and can confirm it happens there as well without the workaround:
![image](https://user-images.githubusercontent.com/42678262/184479780-8539c027-6496-4cc1-9d70-0b7d261f5632.png)

I still hope this gets looked into.

**Comment by CrezyDud** [comment]
thanks for the workaround, i made a sub animgraph with the fix, i connect animations to it that dont have a morph

**Comment by aylaylay** [comment]
So this is an issue with the base model feature?

**Comment by CrezyDud** [comment]
the fbx in the addons citizen folder that comes with sbox, doesnt have material nor shape morphs in it, which i used to animate

**Comment by LazyDuchess** [comment]
> So this is an issue with the base model feature?

I think it's an issue with animgraph, as if you add a custom animation without morphs directly into the citizen.vmdl you get the same result

**Comment by aylaylay** [comment]
give me steps and a animation to reproduce this

**Comment by CrezyDud** [comment]
use citizen.fbx from sbox/addons/citizen/models/citizen/citizen.fbx
make animation, export as fbx, open model doc, use base model "citizen"
add fbx animation, export, make animgraph, use exported model as animgraph
add animation to animgraph, connect to finished pos, and click
![grafik](https://user-images.githubusercontent.com/84625713/184509910-b4953d87-8ce8-4376-87bd-a101349ed640.png)
on the walking dude

**Comment by aylaylay** [comment]
I'm not making an animation to reproduce this.

**Comment by CrezyDud** [comment]
> I'm not making an animation to reproduce this.

then just export as-is,
you dont even try

but it will work anyway

**Comment by CrezyDud** [comment]
you dont do an animation, you dont have to cloes

**Comment by DissolveDZN** [comment]
i have the same issue lol why is this closed

**Comment by aylaylay** [comment]
It'll be fixed when someone competent gives repro steps and files

**Comment by ccuntd** [comment]
you can't close an issue because "i gave you not good enough"
this issue exists, am i disruptive now?
i gave you an animation file in the issue post (up at top)
you use my simple step-by-step and you'll know and maybe get someone to fix it
closing, a bug, that still exists, doesn't help
