### ISSUE TITLE
UserInput.IsPressed() unreliable

### ISSUE THREAD

**Issue by Jake-Rich** [Facepunch/sbox-issues#24]
When using Player.Tick() `IsPressed()` works reliably on the local machine but on remote machines it will fire multiple times.

When using `Panel.Tick()` it will fire multiple times on the local machine and remote machine and won't ever fire when setting your fps at 30.

**Comment by justinbrick** [comment]
For the Panel.Tick you are supposed to be grabbing input from the Player class, Panel.Tick runs every frame while Player.Tick runs every update, which is why Input.Pressed is firing multiple times. The solution for this if you're creating a menu is to create static controls for your class and call those methods through Player Tick.
As for Player.Tick, input gets checked on both client and server, perhaps try checking for IsClient or IsServer before doing whatever you're trying to do?

**Comment by Jake-Rich** [comment]
Inside `Panel.Tick` I was using `Player.Local.Input` and static fields to access them. I also surrounded everything with IsClient and it still wasn't working.

**Comment by justinbrick** [comment]
You have to use Player.Tick is what I'm saying though, if you get Player input through Panel tick it's going to get called multiple times

**Comment by Jake-Rich** [comment]
I tried both Player.Tick & Panel.Tick and both were unreliable for remote players, while Player.Tick was at least reliable for the local player.

**Comment by garrynewman** [comment]
Player.Tick should be, and is in my experience, 100% reliable. 

Player.Tick is only called clientside for the local player. If it's being called clientside for remote players then there's something going wrong.

**Comment by Jake-Rich** [comment]
In BasePlayer class:

```csharp
protected override void Tick()
{
	if ( IsClient )
	{
		using ( Prediction.Off() )
		{
			if ( Input.Pressed( InputButton.Score ) )
			{
				InventoryPage.Instance.ToggleInventory();
				Log.Info( "Pressed" );
			}
			else if ( Input.Released( InputButton.Score ) )
			{
				Log.Info( "Released" );
			}
		}
	}
}
```

![image](https://i.gyazo.com/thumb/1200/479278d834defd7d534fa4d3b4e9de9c-png.jpg)

As you can see it fires off Pressed and Released events multiple times in a row. It doesnt matter if `IsClient` is first or `Prediction.Off()` is first, or if `Prediction.Off()` is removed.
