### ISSUE TITLE
Whitelist XML loading classes

### ISSUE THREAD

**Issue by rtm516** [Facepunch/sbox-issues#257]
**What can't you do?**
Load xml using the example below

**How would you like it to work?**
No whitelist errors

**What have you tried?**
```csharp
Primitive = new XmlDocument();
Primitive.Load( new MemoryStream( FileSystem.Mounted.ReadAllBytes( GetCurrentDataPath() ).ToArray() ) );

var aabb = Primitive.SelectSingleNode( "//Bounding/AABB" );
var min = new Vector3( aabb.Attributes["minX"].Value.ToInt(), aabb.Attributes["minY"].Value.ToInt(), aabb.Attributes["minZ"].Value.ToInt() );
var max = new Vector3( aabb.Attributes["maxX"].Value.ToInt(), aabb.Attributes["maxY"].Value.ToInt(), aabb.Attributes["maxZ"].Value.ToInt() );

SetupPhysicsFromAABB( PhysicsMotionType.Dynamic, min * LoadScale, max * LoadScale );
```

**Additional context**
This is what I have locally to get it working
```
System.Private.Xml/System.Xml.XmlDocument
System.Private.Xml/System.Xml.XmlDocument..ctor()
System.Private.Xml/System.Xml.XmlDocument.Load( System.IO.Stream )
System.Private.Xml/System.Xml.XmlNode*
System.Private.Xml/System.Xml.XmlAttribute*
```

**Comment by rtm516** [comment]
Modified a c# xml lib for sbox
https://github.com/rtm516/SboxXml

**Comment by Adesii** [comment]
Bump. Still relevant, especially as a alternative for JSON. like Oppossome said useful for XML based save files or using external tools that have libraries written with xml in mind like the Sprite editor: Tiled.
gonna use the SboxXml for now that rtm516 send, but this seems unnessary, since there shouldn't be any security risk from the XML classes.
