### ISSUE TITLE
Entity trigger_teleport not teleporting players to remote destination

### ISSUE THREAD

**Issue by NSGOmega** [Facepunch/sbox-issues#260]
**Describe the bug**
When tieing a mesh to an entity as trigger_teleport and then assigning it a remote destination the player is not teleported when they come in contact with the entity.

**To Reproduce**

1. Go to a mesh
2. Tie it to an entity
3. Set it as trigger_teleport
4. Give it a remote destination (in this case I just gave the player_start a name & assigned it to the trigger)

**Expected behavior**
Should teleport the player to the remote destination

**Screenshots**
![image](https://user-images.githubusercontent.com/70560728/119866281-a8e2e980-beea-11eb-9a12-13e348bf9c9e.png)
![image](https://user-images.githubusercontent.com/70560728/119866323-b0a28e00-beea-11eb-9fdd-a6d6955f8f06.png)

[trigger_teleport_test.zip](https://github.com/Facepunch/sbox-issues/files/6555611/trigger_teleport_test.zip)

**Comment by robotboy655** [comment]
This affects every single thing that tries to move the player object from the native code. Related issue: https://github.com/Facepunch/sbox-issues/issues/224

**Comment by robotboy655** [comment]
Related issue: https://github.com/Facepunch/sbox-issues/issues/55

I have added a basic trigger_teleport entity. I have took away the unimplemented fields from the .fgd (local landmark, etc) and added a option for the final position to work more like world portals. Let me know what you think, and if you want any other options.

Feel free to close this if you feel this issue is solved.

**Comment by NSGOmega** [comment]
Appears to be fixed. Thanks!
