### ISSUE TITLE
"broken" weapon_shotgun and weapon_pistol entity

### ISSUE THREAD

**Issue by gabengaGamer** [Facepunch/sbox-issues#394]
Entities weapon_shotgun and weapon_pistol in the hammer editor are not working (obsolete) but after compilation of the map they will spawn
**In Hammer**
![image](https://user-images.githubusercontent.com/54669564/123297221-0ab16600-d520-11eb-961f-48cff7fe3227.png)
**In Game**
![image](https://user-images.githubusercontent.com/54669564/123297299-2157bd00-d520-11eb-983c-84449c1d142a.png)

Demo: https://www.youtube.com/watch?v=QUpgXmev4lA

**To Reproduce**

1. Create obsolete weapon_pistol or weapon_shotgun entity
2. Compile map
3. Magic

I think it is worth adding these entities to the FGD base, as well as giving the opportunity to customize them.

**Comment by robotboy655** [comment]
I guess this is more of an oversight/NYI situation with remote gamemodes. The entities are in the `.fgd`s (albeit they dont currently have a editor model set) if you have the Sandbox gamemode locally installed.

https://github.com/Facepunch/sandbox

**Comment by robotboy655** [comment]
Basically you have got to install the gamemode into your `addons/` folder for the entities from it to appear in your Hammer Editor. (Sandbox in this case)
I think that's a reasonable expectation/requirement. Otherwise you'd just end up with a bunch of irrelevant entities from all the random gamemodes you have played.
