### ISSUE TITLE
Sbox wiki 401 Access Error

### ISSUE THREAD

**Issue by xrayhunter-git** [Facepunch/sbox-issues#412]
**Describe the bug**
I didn't know where to report this issue too.
I'd like to edit and contribute to the wiki page, my UserID `687321`. I don't know if I was shadow banned or something.

I've chatted about this is #developer-chat in discord, and it seems like I'm not the only one that has this issue.

**To Reproduce**
1. Register a new account.
2. Log in to the account.
3. Edit a page.
4. 401 Error - "You need to be logged in to see this page."

**Expected behavior**
1. Log in to the account
2. Edit the page.
3. Page was edited.

**Screenshots**
![image](https://user-images.githubusercontent.com/3002612/123566466-9e7b7000-d774-11eb-8535-9b87e212dba0.png)
https://wiki.facepunch.com/sbox/RPCs~edit

**Additional context**
Discord Contact: xrayhunter#0101
Browsers used:
Chrome - (Has extensions, though running in incognito, aka no extensions same result)
Edge - Same result (Also has some issues graphically duplicating, but not related with this ticket)
Firefox - Same result.

Thank you!

**Comment by garrynewman** [comment]
This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed. 

If it is fixed feel free to close the issue yourself <3

**Comment by xrayhunter-git** [comment]
> This should be fixed/added on next build, which usually takes about 5 minutes to hit Steam. Please reply to this post to let me know if it's fixed.
> 
> If it is fixed feel free to close the issue yourself <3

Thank you! It works!

**Comment by Grodbert** [comment]
I don't like having to reopen a closed issue, but on xrayhunter's suggestion I will, he and I were having the exact same problem, just not he told me it was fixed but I'm still having the same problem, error 401, need to be logged in to see that page, despite being logged in already.

I am using the latest version of chrome (91.0.4472.114), 64 bit, latest version of Steam and tried both without any extension, in anonymous mode and with a different wifi.

Here is my user ID in the wiki https://wiki.facepunch.com/sbox/~user:674479 , I too am worried I was shadow banned since I did a couple of stupid things in the past, which in part I hope that's the case because it would mean the error was fixed and it is a bummer that I had to reopen it.

**Comment by thegrb93** [comment]
Happened to me before a month ago. I found if you're logged into the gmod wiki then trying to use the sbox wiki, or if you're logged into the sbox wiki and try to use the gmod wiki, then you get a 401/403.

**Comment by Grodbert** [comment]
I get error 403 when trying to get into the other Wikis, when logged in the S&box wiki on the right I can only see the S&box wiki, but if I log out I will be able to also see the Rust, Gmod etc. wikis, if I go there and try to log into my Steam account, I get error 403, not authorized.

**Comment by xrayhunter-git** [comment]
Re-opened this issue; I don't currently have this issue, but it seems that @Grodbert and some others still have these issues.
