### ISSUE TITLE
Upload game specific scenes on Asset.Party

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4171]
### For?

S&Box

### What can't you do?

Up until now sharing community made maps has been limited and tedious.

- Tedious because for each single game you'd have to plead to the mapper to add your game specific logic inside of their map and reupload it, which becomes a mess after 3-4 games.
- Limited because some games have maps/levels that do not function like we've seen so far. A few examples are Bomb Survival and Grubs, which use the SDF library to generate terrain.

In Bomb Survival's case I load the terrain using textures for each different layer and material, then I also have a texture to show where to place bombs which doesn't let me place exactly where the bombs go.
Now that we have the scene system I can comfortably load the terrain and manually place bombs.
As for community made maps, I could just load every scene related to my game and play it.

### How would you like it to work?

We can have base maps uploaded to asset.party, same as it has been up until now.
Then we can have a section on a game for community content, if allowed, where you can browse the scenes made for the game.
Right now the scenes would only be maps with the game logic in them, it would only require a reference to the map and not the map itself, this way it can keep itself up to date and also remain kilobytes in side.
Code wise, it would be similar to how map rotation works right now. Load a list of scenes available, pick which one to play, download it and play.

### What have you tried?

For Bomb Survival I was thinking of setting up my own server and creating my own tools to make maps and upload the textures required for each building material and layer, but I have 0 experience on any of those and this sytem would make it a breeze.

**Comment by garrynewman** [comment]
We should really hold off on this until we totally figure out what's happening with maps in scenes. We don't want to get into the situation where people are uploading scenes just to load a map.

**Comment by anthonysharpy** [comment]
IMO the Italian man is correct

- Maps are assets, just like models or sounds. It should be possible to upload both compiled maps and uncompiled .vmaps on asset.party. These then can be used in scenes however people want. Hammer should be kept mostly as-is as a geometry/level editor, with QOL improvements. Maybe one day things like lightmapping can (and probably should) be taken out of Hammer and put into the editor directly? Once that happens there'll be no need to be able to upload compiled maps on asset.party, just compiled scenes.
- A scene is made for a particular gamemode. A gamemode can run on any scene that is designed for it. Gamemode publishers can choose whether other people can make scenes for their gamemodes. Scenes get uploaded to asset.party.
- I think the idea of having scenes inside scenes would make the above unnecessarily complicated (e.g. https://github.com/Facepunch/sbox-issues/issues/4150), because then some scenes would be designed to be played and some wouldn't be. So I think this shouldn't be a thing (that's what prefabs should be for).

**Comment by chrisspieler** [comment]
Doesn't this work now? Using the Walker Map template as an example. Published scene packages can reference a parent package (e.g. facepunch.walker)
