### ISSUE TITLE
Add BodyGroup related methods directly to model renderer components

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#4272]
### For?

S&Box

### What can't you do?

I am unable to set bodygroups on the classic ModelRenderer component in code by using the bodygroup name or the bodygroup index, only by changing the exposed ulong property that represents the bit flags for the bodygroups (not practical).

`SkinnedModelRenderer` uses SceneModel, which has a SetBodyGroup method, although it does not support indexes, just names.
`ModelRenderer` uses SceneObject, which does not have that method, so only bitflag magic here.

### How would you like it to work?

I would like all model renderer components to have SetBodyGroup methods, which do the hard work for the SceneObjects/SceneModels internally. It would be useful to be able to set the bodygroups using the name, but also the index.

Example of setting the first bodygroup (named body_group_1) to the 3rd subgroup, using name and index:
`SetBodyGroup("body_group_1", 3)`
`SetBodyGroup(0, 3)`

Also, having the `GetBodyGroup` counterparts would be a good idea, since as far as I know there is no way to get the body group state at the moment.

That would match the old methods used on ModelEntities before the Scene System was introduced.

### What have you tried?

Doing the hard work of converting the bodygroup bitflags, not very fun.

**Comment by aylaylay** [comment]
Added SetBodyGroup to ModelRenderer

**Comment by Gmod4phun** [comment]
Thank you very much :)

**Comment by Gmod4phun** [comment]
Reopening just in case further methods (GetBodygroup / GetBodyGroups) are added

**Comment by aylaylay** [comment]
I'm wary of adding too many functions to this component or if they should be on the sceneobject @garrynewman

**Comment by garrynewman** [comment]
It's worth a conversation. My initial thought was to eventually make all the lower level sceneobject stuff hidden, so all functionality should be on components. I don't know whether that would be a great idea though, since there's advantages to creating scene objects manually, without the overhead of the gameobject system.

So what I would say is, the most walked paths should be on the component.  We shouldn't blindly be copying the api from a sceneobject to it, we should leave more advanced stuff on sceneobject. If we have functions that are on SceneObject and are messy or complicated, or there are 5 ways to do them, we should be thinking of ways to simplify that rather than doubling down on it.

**Comment by aylaylay** [comment]
I have added GetBodyGroup @Gmod4phun
