### ISSUE TITLE
Materials don't recompile when textures are changed with MatEd closed

### ISSUE THREAD

**Issue by RickGreeve** [Facepunch/sbox-issues#4484]
### Describe the bug

when overwriting the textures they don't auto update in the material until you 'reset to default' and 'auto fill using me' 

### To Reproduce

1. drop model in sceneviewer
2. make a change in the source textures the assigned material uses (i.e. the color map)
3. textures don't auto update

### Expected behavior

the textures should update when the source updates
It's quite essential to be able to check back and forth in the engine and painter while texturing.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/125879070/a2053b5f-e378-48ca-a810-20463ebed727

notice how toolbag auto updates and sbox doesn't until I do so manually.

**Comment by Gmod4phun** [comment]
Recompiling the material manually also forces the textures to update. It definitely used to happen automatically though.

**Comment by handsomematt** [comment]
This does work, but you need to have the material editor open - it's always been that way.

The intended workflow from Valve would be that you use the preview model in material editor whilst modifying the material.

We can likely make it work without needing material editor but need to be careful not to duplicate logic or make material editor less responsive because of it. It's a bit of a clusterfuck of code to comprehend.

**Comment by handsomematt** [comment]
I was talking a lot of shit - fixed
