### ISSUE TITLE
Show "all files" in asset browser, in folder view

### ISSUE THREAD

**Issue by kira0x1** [Facepunch/sbox-issues#4556]
### Describe the bug

While looking for the generated "MyComponent.cs" i found it in my explorer but the assets browser doesnt display it.

### To Reproduce

1. create a new project
2. go to projects/project_name/code/
3. check to see if files are displayed

### Expected behavior

To display the files in the asset browser

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/13779328/bcc24653-5516-47ed-859d-946a9c8d1a0f)
![image](https://github.com/Facepunch/sbox-issues/assets/13779328/a7f42976-ec75-4151-858e-512093fb8cd0)

### Additional context

os: windows 11 
gpu: 3070ti
ram: 32gb ram, 
cpu: intel i5-12400F

**Comment by garrynewman** [comment]
.cs files aren't assets.. should we show them? Why?

**Comment by kira0x1** [comment]
> .cs files aren't assets.. should we show them? Why?

I suppose when seeing engines like godot, ue5, or unity it was sort of something expected to see in the content browser / assets browser, although it may not be a traditional asset I think that being able to see them in engine could be helpful, it can be misleading to see a code folder and find it empty.
Maybe im just used to viewing it from the lens of a file explorer rather then a asset browser, but I think having a filter for components could useful, tbf it may just be a habit of me used to being able to drag and drop components on scene objects.

**Comment by MrBrax** [comment]
code can be other things than components though, there's already the component list on game objects

**Comment by garrynewman** [comment]
It might make sense to show all files in the folders anyway, even if they're not assets. Let me think on it.

**Comment by fantasticaneer** [comment]
For what it's worth it might be due to my experience with Unity in the past but this is something that tripped me up as well - when using VSCode I'm used to doubleclicking code files in the asset browser rather than using the Explorer tab/loading a folder/etc. It's been at least 4-5 times that I've navigated to the code folder in the asset browser and then gone "oh, right, I have to find it in (vscode/visual studio/windows explorer)".

It helps with deleting code-related files quickly without needing to do it in your code editor / windows, too.
Maybe there could just be 'always show code files' and 'show all files' options similar to the 'show bullshit files' option that already exists in the asset browser's 3-dot dropdown menu?

![Image](https://github.com/Facepunch/sbox-issues/assets/5409303/b3b8a5c4-a3d8-4423-8a0c-5fb976ce8100)

**Comment by kira0x1** [comment]
![Image](https://github.com/user-attachments/assets/74d6312b-d93e-4307-9ee3-85edc24cb72f)
woah ❤️❤️
