### ISSUE TITLE
Generate and allow opening the csproj of an uncompilable project from the welcome screen

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#4566]
### For?

S&Box

### What can't you do?

I'm unable to open projects that have compile errors.
It's making the process of updating old games to the scene system absolutely unbearable as they often contain hundreds if not thousands of compile errors (Shoutout Eagle One).

Not only is it impossible to reach the console at this point to see what the errors actually are, leaving you to only take a quick look at the error notification before it disappears, the fact that the Error List is gone also makes fixing games harder in general.

With the Error List, you could see that many errors were the same and you could trace them back to a single line change that would fix all of them at once. At the current state you need to go through every single error and mindlessly fix it, wouldn't even be a problem if we were able to see more than 3 errors at once through the notification!

### How would you like it to work?

Like before. (Sorry can't find a better way to say it)

### What have you tried?

I've been commenting code out just to get a project to run and rebuild it from the ground up, but now I'm in a bigger mess than before! Save me!

### Additional context

I really liked Tony's error list and I know it's been sort of integrated with the console, but I believe it was more user friendly before.

**Comment by Grodbert** [comment]
This comment is also relevant to https://github.com/Facepunch/sbox-issues/issues/4496 but I'm saying it here because I was told to and it was a team effort from both issues to screw me over.

I could not open any project because there was outdated code that didn't get converted, so it gave an error.
As the average artist, whose best tool to open code is notepad++, this left me unable to do anything while waiting for a programmer to fix it.

To test if this was the problem, I went into my "playground" project that has no code and only models, it opened, but the next time I opened any project (to get a screenshot), it gave me an error about the default pawn.cs file it generates instead, and not of the current project I was trying to open, but of the models playground project.

I deleted the files because I didn't need any code anyways for that project, but now it throws this error, trying to find the same files that gave me the previous error:
![image](https://github.com/Facepunch/sbox-issues/assets/86626409/f8ddfcf3-a764-4e55-94eb-1b97a443f27b)

As you can see, it's not even an error about the project I'm trying to open.
I'm not sure if all "this" was intentional, but it's clearly a bump in the road for many users.

**Comment by garrynewman** [comment]
If we let you open games with errors, then scenes will have broken components and we'll have that issue again.

We could let you open the csproj from the welcome screen?

**Comment by yuberee** [comment]
What about the Error List?
We're unable to reach the console anyways with an uncompilable project, so it wouldn't hurt to pop open the Error List when attempting to do so.
It already shows an error list but from my limited experience it's not nearly as good or accurate.

**Comment by Retroeer** [comment]
Yeah, we can already access the project via right clicking the project, but the error list is a bit more intuitive than the error screen we get right now, maybe if you could click to open directly to the line it's failing to compile and scroll through all the errors and have it update as errors get fixed it'll be a bit more intuitive

**Comment by xezno** [comment]
I added a button to open the solution on the error dialog - you could already access this before by right clicking the project in the welcome screen, but hopefully this is more obvious

**Comment by yuberee** [comment]
This has somewhat been implemented
