### ISSUE TITLE
Newly created .razor.scss files do not work until full s&box restart

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4725]
### Describe the bug

Says on the tin

### To Reproduce

Make a .razor.scss file, it doesn't style the panel at all, close S&box and re-open it, open your project, and now it does style it.

### Expected behavior

I do not want to restart the entire editor and reload the project every time I want to make and style a new Panel.

**Comment by dch-GH** [comment]
> @dch-GH Is this while a game / scene is running? Or just if you create the file and then run the scene it doesn't work?

Either-or. Load up a game project, the scene isn't running, add a new razor +razor.scss file, add it to a panel component, run the scene and the style isn't being applied, restart sbox entirely and now it works.

**Comment by CarsonKompon** [comment]
In my experience it will not load an scss file if you do the following:

1. Create a razor panel with the [StyleSheet] attribute
2. DO NOT create the scss file
3. Render the panel (This is most likely to accidentally happen if you're hotloading the UI as you're making it)
4. You'll get an error that says the scss file does not exist
5. Create the scss file
6. Render the panel again and you will get the same error (likely because it already cached that the file does not exist? just my best guess)

**Comment by kurozael** [comment]
I fixed a bug with hotloading SCSS on panels with StyleSheet attribute - maybe it fixed this as a side effect?
