### ISSUE TITLE
Optimized Builds

### ISSUE THREAD

**Issue by birdbrainswagtrain** [Facepunch/sbox-issues#490]
**What can't you do?**
While debugging, I realized that some very simple methods weren't being inlined. As far as I was able to tell, sbox will only build addons in debug mode. While debug builds are probably ideal for most users, some of us are already working on more compute-intensive stuff, like voxel worlds and interpreters.

**How would you like it to work?**
Ideally there would be some kind of toggle, either in-game or in the addon config. Like I said, I think debug builds are still probably a sane default, but it would be nice to have the choice.

I'm not 100% sure, but I believe optimizations can be controlled on a per-assembly basis. It *might* be as easy as changing the `OptimizationLevel` on `CSharpCompilationOptions`, but I couldn't be bothered to hack on it that much.

**Comment by GGG-KILLER** [comment]
Maybe this should be a separate issue since it can't be enabled per assembly, but enabling PGO would be nice as well.

There is static and dynamic PGO and I think it would be worthwhile testing if any of them make a difference in performance.

**Comment by Rohansi** [comment]
IIRC debug builds only have a few minor changes from release. The real optimization which handles inlining etc. is done by the JIT. We aren't explicitly disabling optimizations so it might just be turning them off automatically because you attached a debugger. Have you tried comparing performance with a sbox.exe process which has never had a debugger attached to it?

@GGG-KILLER How and why would you do PGO on addons?

**Comment by GGG-KILLER** [comment]
I've ran programs in release builds with the debugger attached before (even for this issue itself) and the JIT doesn't disable itself because of that.

I've compared the compiled code of a program in debug and release mode and the game is generating debug code.

Debug:
![unknown.png](https://user-images.githubusercontent.com/5892127/126906582-f33e4379-000d-4b96-a235-a5efbd27a91f.png)

Release:
![unknown-1.png](https://user-images.githubusercontent.com/5892127/126906600-9aad4914-d35e-478c-ae2b-99b8cfab36e2.png)

The optimize flag on compilation is what defines whether or not the compiler will do some (very fundamental since Roslyn team's opinion on the compiler doing optimizations is that it shouldn't and that the JIT should do everything) optimizations and sets whether or not the assembly will be optimized.
Debug mode adds an aseembly wide attribute: ```cs
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
``` that has a flag that disables optimizations for that whole assembly while Release builds only have this: ```cs
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
```
So yes, the issue is that sbox isn't building in Release mode.

Now, about PGO, that's a JIT toggle that affects the entire program iirc and it would be something that the entire game would get, not only addons. And I'm sure everyone would benefit from call devirtualization and other things PGO enables the JIT to do.
Although I do have to warn that static PGO wouldn't be a good fit for this case as it requires gathering data in advance and dynamic PGO is still experimental iirc requiring you to set some `COMPlus_*` env vars.

**Comment by GGG-KILLER** [comment]
The env vars required to enable PGO are:

```
# Enable OSR
ENV COMPlus_TC_OnStackReplacement 1

# Enable PGO
ENV COMPlus_TieredCompilation 1
ENV COMPlus_TieredPGO 1
ENV COMPlus_JitClassProfiling 1
ENV COMPlus_JitEnableGuardedDevirtualization 1
ENV COMPlus_JitInlinePolicyProfile 1
ENV COMPlus_TC_QuickJitForLoops 1
```

**Comment by Rohansi** [comment]
Cool, so that attribute is probably the culprit. We'd for sure need some way to switch between debug and release in the near future. Most players are not going to need debug capabilities so it's just a waste. Not sure how we'd switch between them yet so we should discuss that here.

For PGO I'd create another issue. I doubt we'll do static PGO but dynamic sounds interesting for the more distant future.

**Comment by birdbrainswagtrain** [comment]
Apologies for the late response. 

IMO it would be best to default to debug for locally built addons, and release for addons loaded from the web. Then maybe just a convar, setting in options, or setting when starting a server to override this behavior?

I thought about making the override per-addon, since then only addons that want a specific configuration could request it, but it seems like something that would get annoying to manage, and garry doesn't seem to like the per-addon config files.

**Comment by GGG-KILLER** [comment]
So, I don't have the game but I've seen that there's a `-tools` swich that enables the asset browser and allows you to launch VS and VSCode and the suggestion I came up with is a `-debug` switch as well.

My reasoning for a CLI switch is so that people wouldn't be able to release addons with Debug builds (accidentally or intentionally, addons should always have Release builds for best perf possible).

**Comment by handsomematt** [comment]
builds are now optimized when compiled for backend upload
