### ISSUE TITLE
Project assets aren't loaded when joining via new instance in editor

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#4912]
### Describe the bug

Local models/textures etc aren't mounted/loaded when joining with a new instance when playing a scene in the editor.

Game code runs however.

### To Reproduce

1. Load scene
2. Play scene
3. Join via new instance

### Expected behavior

Assets should be mounted and loaded from the local install to not have to constantly upload updated assets

### Media/Files

![20240221105907_1](https://github.com/Facepunch/sbox-issues/assets/1517911/003fc45a-6de9-48f2-9c21-b2facd5a1a72)

```
2024/02/21 11:35:41.8376	[GameMenu] Loading Network Assembly: [package.base]	
2024/02/21 11:35:42.9318	[GameMenu] Loading Network Assembly: [package.local.newproject]	
2024/02/21 11:35:43.1992	[engine/ResourceSystem] Error loading resource file "models/ball_open.vmdl_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/21 11:35:43.1992	[engine/ResourceSystem] Error loading resource file "models/ball_closed.vmdl_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/21 11:35:43.2988	[engine/ResourceSystem] Error loading resource file "models/water.vmdl_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/21 11:35:43.3183	[engine/ResourceSystem] Error loading resource file "models/cup.vmdl_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/21 11:35:43.3320	[engine/ResourceSystem] Error loading resource file "models/ramp.vmdl_c" (Error: ERROR_FILEOPEN: File not found)	
2024/02/21 11:35:43.3489	[engine/ResourceSystem] Error loading resource file "models/sbox_props/security_shutter/security_shutter.vmat_c" (Error: ERROR_FILEOPEN: File not found)	
```

**Comment by garrynewman** [comment]
This is a known issue, although I suspect the issue isn't public.

- [ ] Download asset list for developer hosts
- [ ] Download via our own HTTP proxy

**Comment by Guilhem-Pech** [comment]
Same issue with cloud assets

https://github.com/Facepunch/sbox-issues/assets/15714248/2f31848f-fe87-453d-84c1-f57786fd9e82

**Comment by Gmod4phun** [comment]
Yeah this is annoying, can't really test things out with assets constantly missing

**Comment by kira0x1** [comment]
This keeps happening to me all the time, very frustrating to use cloud assets atm.

Just happened with a opium model and even reinstalled sbox because i wondered if deleting all the local data for that model would fix it, but it just broke it even more i think.

I actually found a funny fix by unticking "has assets" in the project settings, reloading the project, then ticking has assets again.

![image](https://github.com/Facepunch/sbox-issues/assets/13779328/8aa5e1a3-182c-402f-88ec-92ca5f8f27b3)

https://github.com/Facepunch/sbox-issues/assets/13779328/eb115e27-d665-4a9f-9b5b-1dc1cda643c2

**Comment by MrBrax** [comment]
i'm reading this got added recently?
