### ISSUE TITLE
Controller Vendor Features

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#4915]
There's a bunch of features that individual vendors implement for their controllers which SteamInput implements, but they're vendor specific implementations.

There's lots of questions to be answered here from (https://partner.steamgames.com/doc/api/isteaminput) before we start going in and implementing all these features.

TriggerRepeatedHapticPulse - does this work on xbox and ds5? if so, do those inputted values feel the same on all vendors? If they don't, we'd have to implement per-vendor presets..

TriggerVibration/TriggerVibrationExtended - does this work on all vendors? does it feel the same? I believe `leftTrigger` and `rightTrigger` only work on xbox controllers..

SetLEDColor - worth implementing for people to use, or do we refrain and hook up colors ourselves when we support multiple controllers?

Switch Joycons/DualSense let you pipe audio through to the controller, I don't know what's exposed their on the SteamInput API (if at all)

How do we want to implement haptics? Assumedly not raw access, we'd want to define presets somewhere, and let people use them? Do we want a curve editor for it? (Like this haptic composer that @xezno sent me) 
![image](https://github.com/Facepunch/sbox-issues/assets/22372616/ca0235e5-4cb0-45b2-a41e-a172fb211a39)

**Comment by xezno** [comment]
Generally it's usually not worth implementing stuff for specific vendors, but from my perspective at least, it's worth supporting some of the DualSense specific stuff because I can see other vendors eventually following suit with new devices/controllers. I'm not sure about general usage (controllers aren't covered by the steam hardware survey) so I can't comment on how many people are using the different controllers - maybe it's worth collecting that data ourselves somehow?

> TriggerRepeatedHapticPulse - does this work on xbox and ds5? if so, do those inputted values feel the same on all vendors? If they don't, we'd have to implement per-vendor presets..
> Switch Joycons/DualSense let you pipe audio through to the controller, I don't know what's exposed their on the SteamInput API (if at all)

We could implement haptics as a 'high-detail' representation that we automatically downscale/downsample to something other controllers can use (like standard vibrations for xbox controllers).

> I believe leftTrigger and rightTrigger only work on xbox controllers..

I'm not entirely sure what the best way to do adaptive triggers is. Xbox and Playstation appear to handle this very differently, with dualsense having loads more parameters to use that we can't just emulate or downscale for less capable devices.

> How do we want to implement haptics? Assumedly not raw access, we'd want to define presets somewhere, and let people use them?

My view on this is that we have some nice curve editor but we could give users raw access in case they need it.. though I can't think of any use cases that a haptic pattern editor wouldn't solve.

> SetLEDColor - worth implementing for people to use, or do we refrain and hook up colors ourselves when we support multiple controllers?

Also worth noting that Windows has a [dynamic lighting API](https://learn.microsoft.com/en-us/windows-hardware/design/component-guidelines/dynamic-lighting-devices) for other devices now, like mice and keyboards. We could either support this ourselves or wait for steam input to support it - but I think it would be quite a nice thing to have here too?

**Comment by DevulTj** [comment]
I think we're in a good place now.

**Comment by WujekFoliarz** [comment]
> I think we're in a good place now.

Sorry for bringing this thread back up, but if you want adaptive triggers and LED for the DualShock 4 or DualSense, I've rewritten the original Sony library and made it free to use
https://github.com/WujekFoliarz/duaLib

**Comment by cmcskimming** [comment]
Still no adaptive triggers for DualSense controllers. I don't know if you guys have ever experienced the PS5 controllers' adaptive triggers but it is not even comparable to the xbox's trigger vibrators. The current system just completely neglects all the cool features of the DualSense controllers so it'd be great if we got raw access like xezno mentioned.

Things that are currently neglected for DualSense controllers that I would like to see supported:
adaptive triggers (currently we can't adjust their resistiveness or even vibrate them) <- this one above all else
LEDs
microphone
speaker
touch pad
