### ISSUE TITLE
Package System

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#5053]
# Problem

Duplicated code, hard to get started, lack of "middleware" code. Some people like coding middleware stuff rather than the games they go into, we should cater for that.

# Solution

There's a folder in your problem called "Packages". Any folder inside of there is a package, which can be published to asset.party. Packages have their own assets, code, editor, unit test folders. They are their own, isolated projects.

```
MyGameProject
│
└───Packages
    │
    ├───Package1
    │   ├───Assets
    │   ├───Code
    │   ├───Editor
    │   └───UnitTests
    │
    ├───Package2
    │   ├───Assets
    │   ├───Code
    │   ├───Editor
    │   └───UnitTests
```

We will offer a package manager, where you can view and update the packages. They will not auto update. The expectation is that you download a package and then that code is yours, you commit it along with all your other code. When you want to update the package, you do it manually by opening the package manager and updating. 

# Examples

Say I make an awesome editor addon that adds a bunch of tools. I can now share this as a package and other people can install it. I don't have to be scared to push new updates, because their on-disk version won't change.

Say I make a NPC pet system. I can publish that as a package, with the editor. Some people can download it and use it as it is. More advanced users can download it and edit the package directly. 

# Considerations

This is thought out in a way that the project is king. We still have a single project, without external dependencies. There should never be a situation where you have to check out 3 different projects to get a project working.

- Packages are isolated, they can't reference game code
- Packages could reference other packages, with some work
- Should packages be their own assemblies, or should we compile them all together
- We should formalize the folder structure in terms of where editor folders can be, can't be. What the code folder should be named, where assets can be stored. Right now it's a wild west because you can define them to be anywhere, and that sucks.

# Naming

We can't call them Packages. That name already exists. We need a different name.

**Comment by ScoutWozniak** [comment]
With editor tools specifically, would they have to be sandboxed then?  It feels like it could be a risk as like the docs say, they can do almost anything and having potentially malicious code available to download like that isn't the best idea.  Also having the code be able to be edited by the user but also updated through asset party feels like it could get confusing quite fast.  Otherwise it does sound like a good system.

**Comment by garrynewman** [comment]
No they wouldn't need to be sandboxed. Downloading and running is at your own risk, same as downloading packages from nuget, same as downloading from unity asset store.

**Comment by Game4Freak** [comment]
So I guess this will be a direct replacement for the libraries we had before, with the neat addition of editor tools.

But how about addons?
Will they become packages too at some point?

There are roughly 2 types of addons:
- Library specific addons
- Game specific addons

Library specific addons are just simply package specific addons.
But game specific addons will probably require the game to have a API package, they will depend on instead of the actual game as it seams counter intuitive having direct game dependencies with the package system.

**Comment by garrynewman** [comment]
This isn't about addons

**Comment by anthonysharpy** [comment]
> Packages have their own assets, code, editor, unit test folders ... The expectation is that you download a package and then that code is yours, you commit it along with all your other code.

The only downside I can think of is that people will make super big packages with lots of assets, and then once you include a few of these in your project you suddenly have a 3GB git repository, which gets painful really quick

Maybe the solution is to make it so packages can only be added via asset.party, and so all the assets are hosted there rather than in your Git repository. Or maybe that's already the plan

**Comment by Game4Freak** [comment]
> This isn't about addons

Yeah I though so, I guess my comment totally missed my point as I just wanted to make sure that addons are compatible with it.
I love creating "middleware" stuff so addon and version compatability is really important to me :)

As this basically replaces the libraries we had before, addons (e.g. new dogs for the pet system) would need to reference the packages aswell.
This requires some proper version management for compatability (Addon is compatible with the package version the game uses).
The package system gives you version management but you have to be careful with the downloaded packages, as modifying them breaks the version as it's a new custom version at that point.
So it's probably better if the package downloads are readonly or even precompiled and when you want to modify them, it creates a new version or package (kind of like the libraries we had before but with version management).

Also it's pretty easy to get addons mixed with packages as a pet system could be a package or a addon

**Comment by SGde3a** [comment]
Unitys package manager covers a lot of those issues.

A package of 4k skyboxes may be well over 1GB, but the package is yours once downloaded and you can delete whatever you want. Updates to the package display an update icon next to the package. If you update the package it does not auto-import. If you import it shows you a scrollable list of all assets, and those that are to be updated contain a green tick, if you click import it updates those with the tick.

If package updating breaks the package for all users regardless of package state, it's the package developers problem, as no one can update. If the user broke their package, it's their problem and reinstalling the package will fix.

Some packages in Unity also have an installer-type prefab file, which can identify the target system and update materials from one type to another in the case of engine changes or other compatibility differences which may break the package.

As far as being in control it's hard to beat, but you do download gigabytes, and there are files everywhere.

**Comment by garrynewman** [comment]
So I was thinking "Kits" or "Toolkits" might work, as they're different enough from everything else
