### ISSUE TITLE
Add a replacement system for GameEvents

### ISSUE THREAD

**Issue by Gmod4phun** [Facepunch/sbox-issues#5055]
### For?

S&Box

### What can't you do?

Since the entity system was removed, so were GameEvents. With those we had the ability to globally listen to events such as physics pre/post step, entity creation, hotload, and so on.

While some of these (like physics steps) are available per-component, that requires you to create a new component and add it to every single thing which you want to do something. That is impractical.

A better solution would probably be to expand the GameObjectSystem we have currently.

### How would you like it to work?

I would like it to work by being able to listen to certain events, like a gameobject/component being created, sound being played, physics collision happening, and various other useful things. Most likely as an expansion to the already existing GameObjectSystem.

### What have you tried?

Using the currently limited GameObjectSystem.

**Comment by garrynewman** [comment]
The problem with the event system was how soft coded it was. We wanted to add parameters and stuff, but then the person adding the event needed to know what the parameters was, it was kind of messy.

The obvious alternative is if we add things like `Scene.GameObjectCreatedEvent` and you can be like

```
GameObjectCreatedEvent += MyEventCallback;

void MyEventCallback( GameObject obj )
{

}
```

This works, and it works in the whole c# ecosystem, but I don't love it. I don't really love having to unsubscribe from events, and adding that burden onto other developers.

There might be a middleground system here somewhere though.

**Comment by peter-r-g** [comment]
> The problem with the event system was how soft coded it was. We wanted to add parameters and stuff, but then the person adding the event needed to know what the parameters was, it was kind of messy.
> 
> The obvious alternative is if we add things like `Scene.GameObjectCreatedEvent` and you can be like
> 
> ```
> GameObjectCreatedEvent += MyEventCallback;
> 
> void MyEventCallback( GameObject obj )
> {
> 
> }
> ```
> 
> This works, and it works in the whole c# ecosystem, but I don't love it. I don't really love having to unsubscribe from events, and adding that burden onto other developers.
> 
> There might be a middleground system here somewhere though.

Could take a page from Godot's book here with their implementation of signals in C#. A user can define a delegate that describes your event and codegen creates the C# event for you.

```cs
//
// Producer code
//
// Optional parameter to define C# event name?
[Event]
delegate void OnFirstEventEventHandler();
[Event]
delegate void OnSecondEventEventHandler( GameObject first, GameObject second );

// Codegen a nice invoke wrapper?
OnFirstEvent?.Invoke();
OnSecondEvent?.Invoke( cock, balls );

//
// Consumer code
//
OnFirstEvent += FirstEventCallback

void FirstEventCallback()
{
}

protected override void OnDestroy()
{
  // Codegen or reflect this away from the user
  OnFirstEvent -= FirstEventCallback
}
```

https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#custom-signals

**Comment by Game4Freak** [comment]
How about using interfaces in a similar direction as the `INetworkListener`.

You could define a event with the interface like this:
```c#
[Event]
public interface IDeathEvent
{
	void OnDeath( GameObject obj);
}
```

Then have the event system generate a wrapper instance of the interface and return it like this:
```c#
public void Kill( GameObject obj )
{
	EventSystem.Get<IDeathEvent>().OnDeath( obj );
}
```
In the wrapper instance it gets all enabled components in the scene of the interface type and calls the method on them.

**Comment by garrynewman** [comment]
> https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#custom-signals

I don't really understand how that is any different to the c# events that I just mentioned

**Comment by garrynewman** [comment]
> How about using interfaces in a similar direction as the `INetworkListener`.

That could be something

**Comment by LeQuackers** [comment]
Bouncing off of Game4Freak's idea, what about "pushing up" and "pushing down" events in the hierarchy?

e.g. Say we had some `GameObject` structure like this:
```
Root
│
├── Blue Team
│   ├── Player 1
│   └── Player 2
│
├── Red Team
│   ├── Player 3
│   ├── Player 4
│   └── Player 5
│
└── Yellow Team
    ├── Player 6
    ...
```

- If we "pushed up" an `IDeathEvent.OnDeath` event originating from **Player 1**, then every `IDeathEvent` ancestor (including itself) would run, so **Player 1**, **Blue Team**, and then **Root** would see the event if they implemented `IDeathEvent` or had `IDeathEvent` components
    - If you wanted to listen for `IDeathEvent` events originating from anywhere, then you'd add an `IDeathEvent` component to **Root**
    - If you only wanted to listen for `IDeathEvent` events originating from somewhere inside **Blue Team**, then you'd add an `IDeathEvent` component to **Blue Team**

- If we "pushed down" some `IGameStartEvent.OnStart` event originating from **Root**, then every `IGameStartEvent` descendant (including itself) would run, so in this case every `GameObject`/`Component` that implemented `IGameStartEvent` would see the event because it originated from the hierarchical root

- If we "pushed down" some `IPlayerJoinedTeamEvent.OnJoined` event originating from **Blue Team**, then every `IPlayerJoinedTeamEvent` descendant (including itself) would run, so **Blue Team**,  **Player 1**, and **Player 2** would see the event if they implemented `IPlayerJoinedTeamEvent` or had `IPlayerJoinedTeamEvent` components
    - Same deal with `IDeathEvent` events; if you only wanted to listen for `IPlayerJoinedTeamEvent` events being sent to **Blue Team**, then you'd add an `IPlayerJoinedTeamEvent` component to **Blue Team**

The problem with this though is that it requires the `GameObjects` to be parented in a particular way, which will definitely cause some annoying hierarchy limitations because of parents transforming child positions when they move.

If there was an "organizational parent" then this might be practical; what are your thoughts on adding some `bool GameObject.IsOrganizational { get; set; }` or `bool GameObject.TransformChildren { get; set; }` property for disabling relative transforms?
