### ISSUE TITLE
Adding bones to Citizen causes strange deformations

### ISSUE THREAD

**Issue by Kabubu2** [Facepunch/sbox-issues#5102]
### Describe the bug

I want to add bones to Citizen by adding a mesh to make those bones available to make bone merging possible with clothing items that require a little more control such as a bow that requires string control or a cape to flow since cloth sims don't work.

However, when I add a mesh to the model the existing animations have some strange effects. This happens regardless of adding the existing citizen armature or not.

### To Reproduce

Take an asset and rig it to a newly added bone on the citizen armature. Bring that new mesh in the RenderMeshList. It will happen regardless of the markup modifier.

### Expected behavior

It should add the bones to the mesh without altering the existing meshes. Ideally allowing animations that manipulate the existing citizen bones and the new bones to allow for more control over the type of cosmetics people would need for their projects.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/18005111/aa36cf20-faed-4e2f-89d5-ddedd2aba5af)
![image](https://github.com/Facepunch/sbox-issues/assets/18005111/5d2a83b7-73a1-4480-bb24-e844ab48b78e)

**Comment by garrynewman** [comment]
I'm not sure what you're doing here.

Is the citizen model named the same? Could it be conflicting with the existing citizen model?

Maybe @MaxLebled understands this a bit more

**Comment by MaxLebled** [comment]
Unfortunately I don't. Thus is nothing like any of my past experiences any bug I've come across previously, and without the files I can't say whether it's a code issue or an asset issue

**Comment by eEight-dev** [comment]
I think what he is trying to accomplish here is to find a way for the extra bones of an object that aren't bone merged to the citizen's skeleton to basically show animation data.
For example: Let's say a bow's skeleton has a bone called "hold_R", which can be bonemerged to the citizen's skeleton no problem, but then it also has a bone called "string", but because the citizen's skeleton doesn't have it, in the end it won't display any animation data cause it's not bone merged.
This is in animgraph after bonemerging to the citizen skeleton and as you can see there is no animation data for the string or any other bone that is not bonemerged:

https://github.com/Facepunch/sbox-issues/assets/120290229/9c3c08d9-bafd-45e0-9da8-ce198ea781d9

And this is how it should look like:

https://github.com/Facepunch/sbox-issues/assets/120290229/fc19cba9-5732-49a8-8e82-041c86b31d34

I think he is adding these assets and their anims directly into the citizen.vmdl, as an attempt to show the extra animation data from the bones that can not be bonemerged, but something is clearly going wrong.
I have also attempted fixing this by adding the skeleton of the bow directly in the citizen.vmdl, but that ended up completely breaking the citizen's skeleton hold bones hierarchy thus resulting in almost every animation being broken when it came to the hold bones. I also tried other methods but all have failed.
Also the option he has ticked in rendermeshmarkup is used for custom normals.
