### ISSUE TITLE
Warn when trying to call/change things you do not have permission to on networked attributes

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#5196]
### For?

S&Box

### What can't you do?

For both `[Broadcast( NetPermission.HostOnly )]` and `[HostSync]` or `[Sync]` it's hard to know if things are actually called properly or not, it would be nice if we got a warning if you tried to change something you're not allowed to.

### How would you like it to work?

Just a console log warning probably

### What have you tried?

Nothing, just hope for the best with IsProxy and Networking.IsHost checks

**Comment by anthonysharpy** [comment]
The thing is (at least from my experiments), people who don't own an object can still change its transform etc. This is actually a good thing because it means you can make a rudimentary prediction system on an authoritative server (or even a P2P one I guess). I don't think it's something I've tried to implement but the same could be said about [Sync] (maybe we could have the Predictable attribute back, wink wink).

But I agree with [Broadcast] throwing a warning.

**Comment by MrBrax** [comment]
In my experience, changing transform on other clients even as a host does not work, so I think the [Sync] tag still makes sense here.
