### ISSUE TITLE
Input.MouseWheel is ignored when hovering over a UI panel that takes mouse input

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#5302]
Feels bad when you try scrolling but it does nothing, and you have to move your mouse and try again.

As far as I can tell, there's no event such as OnMouseDown that will capture the scroll input.

Here's a simple test project:
![sbox-dev_2024-03-30_03-38-54](https://github.com/Facepunch/sbox-issues/assets/1173137/111b6f01-3f78-48c6-bda8-7e6696307f57)
[scroll_wheel_test.zip](https://github.com/Facepunch/sbox-issues/files/14811570/scroll_wheel_test.zip)

**Comment by CarsonKompon** [comment]
This behaviour seems intended to me because the panel you're hovering might have `overflow: scroll` and you'd want it to scroll that element while not scrolling in the background.

However when I noticed this behaviour for myself a few days ago I did think to myself that there could maybe be something like the following:
```scss
pointer-events: no-scroll;
```
The idea is that this takes pointer-events but not scroll events, allowing you to still get Input.MouseWheel if you're hovering over an element marked with `no-scroll`.

**Comment by ryleigh** [comment]
Thanks! Thought it'd be in `Panel.Event.cs` if it existed but should have searched more.

I'll also blame it on autocomplete rarely working in razor files 😁
