### ISSUE TITLE
GameTransform.LerpTo not reaching the given Transform target

### ISSUE THREAD

**Issue by Mbk10201** [Facepunch/sbox-issues#5321]
### Describe the bug

When we create an transform interpolation, it will never reach the given target transform, weird to explain but here is the confirmation of conna as well ([Programming](https://discord.com/channels/833983068468936704/837215495496663040/1224795642346344468))

### To Reproduce

1. Create a component and add it to a visible gameobject (ModelRender to better overview of the problem).
2. `OnStart()` add for example `Transform.LerpTo( new Transform() { Position = Transform.Position.WithZ(50f) }, 15f );`
3. Launch the scene and check the positions on the inspector, it will never reach the 50 as declared.

### Expected behavior

Change the GameTransform.LerpTo logic to the same as Position, it would be useful in case that we want a shortcut to Lerp Rotation, Position, Scale but all in the same time.

**Comment by kurozael** [comment]
This problem is mitigated a bit with networking transforms as we’ll always have it end up at the last received transform from the server.

Wondering if we fix this particular issue, whether we should have networked transforms follow a separate interpolation process and this public LerpTo method should just take a delta and interpolate similarly to other LerpTo methods i.e. Vector3.LerpTo and Rotation.LerpTo?

Tagging @garrynewman for visibility on this one.
