### ISSUE TITLE
Input.ReleaseAction does nothing

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#5500]
### Describe the bug

if E = "Interact" holding e, then running `Input.ReleaseAction("Interact")` does nothing, and the e is still registered as being held

### To Reproduce

1. `if (Input.Down("Interact")) Log.Info("Interact down");`
2. `Input.ReleaseAction("Interact");`
3. brokey

### Expected behavior

"Interact" should be getting cleared and and need to be held again for the log to send
Oddly enough Input.ReleaseActions does this, but its not exactly usable because this nulls every input
Input.ReleaseAction's functionality should be identical to ReleaseActions, except for the part where it only effects the key you want

**Comment by MD485** [comment]
This might be due to `AccumActionsPressed` being modified in `ReleaseActions()`:
```cs
public static void ReleaseActions()
{
    if (CurrentContext != null)
    {
        CurrentContext.ActionsCurrent = 0uL;
        CurrentContext.ActionsPrevious = 0uL;
        CurrentContext.AccumActionsPressed = 0uL;
    }
}
```
But unmodified in ReleaseAction("action")
```cs
public static void ReleaseAction(string name)
{
    int actionIndex = GetActionIndex(name);
    if (CurrentContext != null)
    {
        CurrentContext.ActionsCurrent &= (ulong)(~(1L << actionIndex));
        CurrentContext.ActionsPrevious &= (ulong)(~(1L << actionIndex));
    }
} 
``` 
Since this is how flipping occurs in `Input.Context`:
```cs
public void Flip()
{
    ActionsPrevious = SavedActions;
    ActionsCurrent = AccumActionsPressed;
    SavedActions = ActionsCurrent;
}
```
In theory the action may stay pressed through the next frame because it was in the `AccumActionsPressed` value.
Retro mentioned it works as expected when using `ReleaseActions()`.  
  
There's also a similar implementation inconsistency between `ClearAction("action")` and `ClearActions()`:
```cs
public static void Clear(string action)
{
    SetAction(action, down: false);
}

internal static void SetAction(int index, bool down)
{
    if (down)
    {
        Actions |= (ulong)(1L << index);
    }
    else
    {
        Actions &= (ulong)(~(1L << index));
    }
}
```
```cs
public static void ClearActions()
{
    Actions = 0uL;
    LastActions = 0uL;
}
```
They don't do the same thing even though the method name implies it will.

**Comment by DevulTj** [comment]
This should be working for you now. I'm gonna give the whole system a spring clean soon.. it's in need of one.
