### ISSUE TITLE
Make line renderer take a list of vector3s or automatically network it.

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-issues#5567]
### For?

S&Box

### What can't you do?

Currently the list of points is gameobjects, networking that is pretty shit.

### How would you like it to work?

I'd like it to just be a list of vector3s, potentially even just a [sync] marked one that automatically networks?

### What have you tried?

To network the line renderer you would have to network spawn all your gameobjects, especially if you're trying to render something dynamically that constantly changes the point count, this is terrible.

**Comment by MD485** [comment]
See this is a complicated issue, because I actually really like Facepunch's implementation.

## What's good about it?

If you're making a line in a game do you wanna have the control points as physical gameobjects in the world you can manipulate manually, or would you prefer to hard code a number and hope it looks right?

You wanna add triggers to the points so that something happens when you pass a checkpoint? You can do that.  

You wanna make the line renderer flow into a door, then through an enemy, then into a window so show the player their path?  
Not only can you do that, but none of those things need to be children of the renderer or have special properties allow that, and the line renderer will dynamically update as their positions do, something you'd have to do manually in Unity.

As someone who used unity a lot and is used to their implementation, and as a knee jerk reaction had the same thought process, I understand what you're saying, but I don't think this change is it.

## But I can't network them!

Something else to consider is that LineRenderers I don't think are practially designed to be networked, the main reason being it's purely a visual component.

ModelRenderers I believe are written the same way, without any sync components, the expectation being that you don't network the ModelRenderers themselves, but instead network the scripts that manipulate them.

## So what I should just give up?

Well, no I didn't say that.

LineRenderers I don't think should be directly networked, this feels strange, it's something visual that's ideally local to the client controlling them. Solutions should be made to manipulate local copies of line renderers as opposed to networking them.

I do like this implementation and think it should stay the default due to it's ease of use, flexibility and simplicity.

However part of the advantage of Unity's implementation is it's low overhead, and it's simple to manipulate through code.

So my personal suggestion would be to simply change this issue to:

## Add a Vector3 LineRenderer

In terms of difficulty this would be trivial.
You take the code they have already, then do:
`public List<GameObject> Points { get; set; }` =>`public List<Vector3> Points { get; set; }`

```cs
        IEnumerable<Vector3> enumerable = from x in Points
                                          where x.IsValid() && x.Active
                                          select x.Transform.Position;
```
=> `IEnumerable<Vector3> enumerable = Points;`

And boom, you're done:
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/b59135e1-d683-4f77-b13f-d77e9af94e7b)
Erm, whoops, err ...
`IEnumerable<Vector3> enumerable = Points;` 
=> `IEnumerable<Vector3> enumerable = Points.Select(x => Transform.Position + x);`
Boom, you're done?
![image](https://github.com/Facepunch/sbox-issues/assets/36082767/b84cfbe4-b0f7-46f7-9a43-6952bb51ce6d)

They'll have to add that bit of logic for Local vs Worldspace, but otherwise a pretty trivial code change.

A secondary advantage this allows for, possibly minor, code optimisations when rendering the line.
Because the _so's line is regenerated every OnPreRender, you can change that code to only run when the points list or GameTransform of the object is manipulated, as opposed to every frame(?).

This would mean adding `SetPoints()` and `RemoveIndex(int index)` and whatever else wrapper methods you would want for manipulating the points and making `public List<Vector3> points;` private, but depending on how things are implemented on the backend it's possible this could have some performance benefit,

**Comment by cmcskimming** [comment]
Garry's gotta switch it to vector 3 the game object points just don't make any sense, if you want to use game objects as your points for the sake of simplicity JUST MAKE A SCRIPT FOR IT. They shouldn't value ease of use for your specific use case over adaptability, not everybody wants to draw lines between game objects.

**Comment by chrisspieler** [comment]
I think it makes sense for the built in components to be as flexible as possible. Defining a position with a GameObject is far more flexible than just using a Vector3. Anyone is free to make a more efficient version of LineRenderer that uses only the exact data they need.

**Comment by MD485** [comment]
Since we have Vector3s now as a part of the default LineRenderer, is it fair to consider this complete?

**Comment by ShadowBrian** [comment]
Yeah I feel like this is closable now.
