### ISSUE TITLE
Add Pause functionality to SoundHandle

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#5581]
### For?

S&Box

### What can't you do?

You cannot pause sounds when played through Sound.Play (SoundHandles)

### How would you like it to work?

```cs
var handle = Sound.Play("snd-test");
handle.Pause();

// Insert some other shit with awaits or something

handle.Resume();
```

### What have you tried?

You *could* use a MusicPlayer but I don't want to play the sound file directly I just want to be able to play the sound like normal.

EDIT: I've also found another odd work-around where you Set `handle.Pitch` and `handle.Volume` to 0 and then back to 1 whenever you want to unpause. It's jank but it works until there's a proper solution.

**Comment by MD485** [comment]
Yeah I've had a similar issue before, found it strange SoundHandles have no pause.

I'm a little confused on the API disparity between MusicPlayers and SoundHandles honestly.
Let's say your shields are low and you want to warn the player, that should be a repeating sound with a fade out, the problem is SoundHandles don't have a repeat, and MusicPlayers don't have a fade out.

Maybe fade out can be added to MusicPlayers, weird it doesn't seem intended to have that functionality already, but they still aren't supposed to be used for game sounds, so it shouldn't make sense to use it for that purpose.

Looking at the code fading out doesn't seem to be a function of SoundHandles at the minute either, but it seems planned.
