### ISSUE TITLE
Add `ComponentList.Add( component );`

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5710]
### For?

S&Box

### What can't you do?

A component doesn't work without a game object. 

And the only possible way to add a component to a game object doesn't allow for component constructors.

### How would you like it to work?

 `Components.Add( component );` adds the component to the game object directly.

It could allow you to use constructors on components like this:
```c#
public class PropComponent : Component
{
    public PropComponent( Model model, Color tint, float health )
    {
        Model = model;
        Tint = tint;
        Health = health;
    }
}
```
```c#
public override OnStart()
{
    var prop = new PropComponent( model, Color.Red, 200 );
    Components.Add( prop );
}
```

### What have you tried?

ComponentList is really locked down. The list is private so there's nothing I can do. 😕
![image](https://github.com/Facepunch/sbox-issues/assets/91832803/34ea93b1-09be-4cf3-ab6a-cf2eadad0a08)

**Comment by MD485** [comment]
If you could do that you could put one component in multiple gameobject's ComponentLists, and if you do that the engine doesn't know when it can delete a component, because it might be referenced somewhere else in the code.

Entity component systems are designed the way they are because if it functioned otherwise the system would break down.
An entity without components is meaningless the same way a component without an entity is.

Why can you not simply do:
```cs
public override OnStart()
{
    var prop = Components.Create<PropComponent>();
    prop.Setup( model, Color.Red, 200 );
}

public class PropComponent : Component
{
    public void Setup( Model model, Color tint, float health )
    {
        Model = model;
        Tint = tint;
        Health = health;
    }
}
```
Practically this is basically the same code, with a similar amount of effort to setup.

Or, if that component simply exists to store data, then why not make it a regular C# class and store that as a field of the component that wants to use it?

While a shared data store can have it's uses, having one class be an "intermediary data class" between multiple classes, muddies each classes responsibilities and makes bugs both easier to make and harder to track down.
