### ISSUE TITLE
"first_person_arms_citizen_4fingers" origin inconsistency.

### ISSUE THREAD

**Issue by eEight-dev** [Facepunch/sbox-issues#5717]
### Describe the bug

The source file for first person citizen arms do not share the same origin as the source file for first person human arms.
First person citizen arms above the grid by many units:
![1](https://github.com/Facepunch/sbox-issues/assets/120290229/3bbc4640-4c18-4eea-9b25-6767f2d7b96c)
First person human arms perfectly at 0,0,0 :
![2](https://github.com/Facepunch/sbox-issues/assets/120290229/34bbb409-baef-4ab3-92f8-e5e6ef22923a)

### To Reproduce

.

### Expected behavior

I expect the source file for first person citizen arms to be at 0,0,0 same as the first person human arms.

**Comment by handsomematt** [comment]
can you check this @MaxLebled

**Comment by MaxLebled** [comment]
This is normal as the VMDL was experimental and just a quick hack — a proper version wouldn't have this offset.

Regardless, this shouldn't be a problem because the arms are always bonemerged onto weapons, so their initial bindPose does not, in theory, matter for these purposes.

So I'm flagging this as "not an issue"
