### ISSUE TITLE
[Hotkey Editor] Add a warning when two actions are assigned to the same button

### ISSUE THREAD

**Issue by rzkid** [Facepunch/sbox-issues#6036]
### For?

S&Box

### What can't you do?

When you accidentally assign another action to an already assigned key (that you may have not known that it was bound), nothing happens. You just trigger both actions, which depending on the affected two actions could lead to varying degrees of disaster.

### How would you like it to work?

Have some sort of warning, pop up perhaps that appears when you bind something to a button that's already "taken".

I don't have a concrete proposal here, anything goes. You could have a whole pop up with options to override new key or cancel the bind, just have a yellow rectangle that pops up or something, or anything inbetween, or all of this, or anything at all, just have a clear warning that notifies the user that something is wrong.

### What have you tried?

Manually noticing something is wrong and manually fixing it.

### Additional context

There's even a default overlap that happens, which is "Select Ring" in the Mesh section and "Toggle Grid Snap", they are both assigned to G by default

**Comment by CarsonKompon** [comment]
It's totally fine to have two binds use the same key. Shortcuts are designed in a way that pressing a key will only invoke the shortcut necessary based on your current focus.

I've been slowly tweaking this for everyone's use cases, but my most recent commit fixes the conflicts of "Select Ring" and "Toggle Grid Snap". If there are any other binds that are taking priority over one-another that shouldn't, please make issues for them :)

**Comment by LVJohnFreeman** [comment]
I think this is a bit short sighted to not have any popup saying you are overriding a hotkey. Most software tell you about it, especially those with a lot of them. It's natural that S&Box will eventually get a ton of em as we get more and more stuff.

![Screenshot_1287](https://github.com/user-attachments/assets/b0b4b7a6-1e3d-481b-b21a-f27f9dad7869)
![Screenshot_1291](https://github.com/user-attachments/assets/882e8125-82f0-4cca-bdbe-53750cb679ef)
![2024 07 31_19 48 03](https://github.com/user-attachments/assets/95d5695f-f9d5-45cc-a7ad-1c4796e8efb2)
![image - 2024-07-31T205713 022](https://github.com/user-attachments/assets/44865d10-2444-45aa-8596-c028cd38eb85)


The problem isn't that you two binds use same key (not at all, i'm also fine with it), the problem is the user potentially not knowing it. Think just some small text at the top that says "X overlaps detected" would do the job. I noiticed my G key doing two things not while messing with binds, but when actually working. That's never a good thing IMO, it should be immediately obvious. Now right now this isn't the biggest problem, but its 100% gonna be annoying UX wise in the long term, might as well have it now.

**Comment by CarsonKompon** [comment]
Added this with my most recent commit. Made it non-intrusive and straight to the point.

![01_13-28-InfiniteHarvestmouse](https://github.com/user-attachments/assets/68b5179a-f5e8-4211-9119-339ec6d9ccf0)
