### ISSUE TITLE
Editor Crashes On Startup (Probably Terrain Related)

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#6041]
### Describe the bug

Basically:

- Was working fine
- Added some terrain to the scene, but it was blank and nothing showed up

![image](https://github.com/user-attachments/assets/2d6eba3a-1426-4dca-a5ea-c89af527dab8)

- Pressing play with terrain would crash the editor
- Installed latest graphics drivers 
- Starting the editor now crashes it instantly on startup, I think because the scene has the terrain in it

![image](https://github.com/user-attachments/assets/2c13e500-dfbe-4a93-8825-f981a6ffbd4e)

[Log.log](https://github.com/user-attachments/files/16442659/Log.log)
[vulkaninfo.txt](https://github.com/user-attachments/files/16442706/vulkaninfo.txt)

Not using any overlay that I know of

Cheers

### To Reproduce

NA

### Expected behavior

Doesn't crash

**Comment by handsomematt** [comment]
Can you zip up the project or at the very least - the scene + terrain asset

**Comment by anthonysharpy** [comment]
@handsomematt Have invited you to a repo for it - if you open Assets/scenes/flat_test.scene it's that scene

**Comment by Rylius** [comment]
Same issue here.

[Log.log](https://github.com/user-attachments/files/16478923/Log.log)
[aftermath_dumps.zip](https://github.com/user-attachments/files/16478942/aftermath_dumps.zip)
[vulkaninfo.txt](https://github.com/user-attachments/files/16478925/vulkaninfo.txt)
[mountains.terrain in a .zip](https://github.com/user-attachments/files/16478967/mountains.zip)

I think this might be caused by not having a camera in the scene.
Tried creating a new scene to reproduce this, added a terrain and it worked fine. Started deleting game objects until something broke and the camera is what did it.

**Comment by aylaylay** [comment]
This is likely fixed now

**Comment by Rylius** [comment]
Seems to work fine here, yeah. Thanks!

**Comment by anthonysharpy** [comment]
@aylaylay Works great, thanks! Feel free to close
