### ISSUE TITLE
Show more information (org in particular) to asset context menu in asset browser

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6043]
### For?

S&Box

### What can't you do?

<img width="370" alt="1722438090969" src="https://github.com/user-attachments/assets/763803e3-db83-430c-bd52-094ecaa553fe">

Sometimes it just helps when you can see what org the asset is from. Could use with some more information.

### How would you like it to work?

Something like

Created by: Facepunch
Last updated: ?
Uploaded: ?
Tris: ?
Draw calls: ?

### What have you tried?

Going to the website every time to show this info

**Comment by CarsonKompon** [comment]
I've updated this popup to have a much nicer layout, but I cannot display information such as LODs/Tris/Draw Calls unless the model is installed (the website has that information cached since it has access to the database). I will probably add those stats to the vmdl inspector so you don't have to dive into modeldoc at the very least.

![image](https://github.com/user-attachments/assets/61047020-3a44-4f3a-bb07-7378f517177a)
