### ISSUE TITLE
Solid tag is applied by default to every gameobjects but doesn't appear in the Gameobject.Tags list.

### ISSUE THREAD

**Issue by Holydh** [Facepunch/sbox-issues#6125]
### Describe the bug

"solid" tag is applied to everything even to objects that returns no Tags when looking through GameObject.Tags.
Also GameObject.Tags.RemoveAll(); doesn't get rid of it.

The actual workaround found by Gvarados is to apply the solid tag, wait some and remove it : 
	GameObject.Tags.Add( "solid" );
	await Task.DelaySeconds( .5f );
	GameObject.Tags.Remove( "solid" );

The discord conversation : https://discord.com/channels/833983068468936704/1267102719873650769/1269746886315737158

### To Reproduce

1. Open minimal game sample project
2. Create tag "cube" in collisions layers. Make the cube collide with itself and with the solid tag.
3. Add cube tag to cubes gameobjects.
4. Place script on the plane to check it's tags :
foreach ( string tag in GameObject.Tags )
	Log.Info( tag );
5. Play. The log should return nothing.
6. Disable collision between cube and solid layer
7. Play. Cube will go through even though the plane still hasn't any tags.
9. Add this script to plane : 
		GameObject.Tags.Add( "solid" );
		await Task.DelaySeconds( .5f );
		GameObject.Tags.Remove( "solid" );
10. Play : cubes now collide with plane.

### Expected behavior

All the tags applied should appear in the inspector and on the GameObject.Tags list.

### Additional context

Steam ID 64 = 76561198072754594
Win10

**Comment by aylaylay** [comment]
Collision shapes no longer add solid tag by default

**Comment by aylaylay** [comment]
Reverted, need to think of a better way to solve this situation

**Comment by aylaylay** [comment]
Games are already assuming collision shapes have solid tag by default internally. If you remove the solid tag after the shapes are created, it should get removed.

**Comment by MD485** [comment]
Can we get some visibility in the UI instead?
![image](https://github.com/user-attachments/assets/b5a6af90-b1d0-48a8-843d-65eb5d49ef38)
I really hate implicit behaviour because from a new developer perspective I don't believe I should ever be asking:
"How was I supposed to know this?"

I know that objects aren't solid by default, but you could add the tag every time a collider is added to the object? 
Then removing the tag through the UI would also remove the tag from the colliders, making it so you don't have to manually add-remove tags or programmatically remove tags which feels like a weird workflow. (You'd still have to do it for procedural GOs)

I understand the desire not to break projects, while I personally think this is something that should happen irrespective of that, the changes outlined above would both fulfill the OP's request and not break an appreciable amount of projects.
(Theoretically a project that procedurally creates gameobjects, then depends on them not having solid tags, but behaving like they have solid tags in terms of raycasting, might break.)

The only edge case I can think of is when deserializing gameobjects/a scene you'd probably need to set the tags last otherwise collider components when deserialized will add solid tags that weren't on the gameobject originally.

**Comment by Holydh** [comment]
> Can we get some visibility in the UI instead? ![image](https://private-user-images.githubusercontent.com/36082767/358336955-b5a6af90-b1d0-48a8-843d-65eb5d49ef38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzk2ODQsIm5iZiI6MTcyNDA3OTM4NCwicGF0aCI6Ii8zNjA4Mjc2Ny8zNTgzMzY5NTUtYjVhNmFmOTAtYjFkMC00OGE4LTg0M2QtNjVlYjVkNDllZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0NTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYmM3ZDdjNzM1ZDdiN2MxYWI3Yzg1ZmNjZmJjNmNiNTY4MjNjMDA4YWE2ZjNjMjM2M2UyNjQzNDkyMmI5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xXeZScEdVcJHnTO1CEagUOBUqGNHbCd2R5mwJpNNY0o) I really hate implicit behaviour because from a new developer perspective I don't believe I should ever be asking: "How was I supposed to know this?"
> 
> I know that objects aren't solid by default, but you could add the tag every time a collider is added to the object? Then removing the tag through the UI would also remove the tag from the colliders, making it so you don't have to manually add-remove tags or programmatically remove tags which feels like a weird workflow. (You'd still have to do it for procedural GOs)
> 
> I understand the desire not to break projects, while I personally think this is something that should happen irrespective of that, the changes outlined above would both fulfill the OP's request and not break an appreciable amount of projects. (Theoretically a project that procedurally creates gameobjects, then depends on them not having solid tags, but behaving like they have solid tags in terms of raycasting, might break.)
> 
> The only edge case I can think of is when deserializing gameobjects/a scene you'd probably need to set the tags last otherwise collider components when deserialized will add solid tags that weren't on the gameobject originally.

I second this. At least seeing all the effective tags applied to a gameobject in the editor would be nice. Now that I know the issue it's allright, but I expect other newcomers to stumble uppon it too.
