### ISSUE TITLE
VR UI Editor (request)

### ISSUE THREAD

**Issue by UnknownDev37** [Facepunch/sbox-issues#632]
Just like Ovr Toolkit, let us move hud elements and bind them to Head or controller, and allow us to hide when out of player picked range and or angle. Presets in this would be nice also.

**Comment by garrynewman** [comment]
This sounds nice, how does it work in OVR Toolkit?

**Comment by walllable** [comment]
> This sounds nice, how does it work in OVR Toolkit?

In OVR Toolkit (Which is pretty much just an app to show desktop monitors and windows in VR in a flexible manner,) you can open a small "editor/window settings" window that allows you to mount them to your controller or headset, along with options to hide them based on angle and distance from the headset.
Here's a video demo: https://youtu.be/18KN79BiCLE?t=16

I figure what the request is is to be able to position UI worldpanels made with SCSS in a way similar to this, so that we can position them and set up hiding values in VR instead of having to trial and error the values manually in code until it's how we want. This could be especially convenient for if we want to hide UI elements depending on the angle/distance of the window, and would make iteration on that faster than trial/erroring in code manually.

**Comment by garrynewman** [comment]
This pre-dated the scene system, so that'd have been a lot harder
