### ISSUE TITLE
CSS rotation and scale transforms don't work properly

### ISSUE THREAD

**Issue by TheEnbyWitch** [Facepunch/sbox-issues#646]
**Describe the bug**
Trying to use rotations and scale on panels doesn't work as it would in the browser.

**To Reproduce**

Use `transform: rotate(30deg)` and compare results both in-game and in the browser

**Expected behavior**
(In Edge)
![msedge_g4NPUkXgeQ](https://user-images.githubusercontent.com/10626859/128768664-2b8893c2-7582-4b3f-a77e-076983bc6c0e.png)

**Screenshots**
If I try to use the same CSS code in S&box, only the top crosshair and the center crosshair are visible
![sbox_fTtWCWcaR7](https://user-images.githubusercontent.com/10626859/128768711-93121b8f-e198-4f25-b428-1c8a036da799.png)

**Additional context**
Attached is the HTML file I used to test the CSS in the browser
[crosshairtest.zip](https://github.com/Facepunch/sbox-issues/files/6957161/crosshairtest.zip)

Here's an image of where I had the lower right crosshair match the desired position (which was completely off in the browser).
The lower left crosshair in the screenshot was rotated in place.
![msedge_jr8vhvowa9](https://user-images.githubusercontent.com/10626859/128768891-aef8ad59-85de-43c7-ba57-62916fe01ef0.png)
![sbox_AtII41xTQ9](https://user-images.githubusercontent.com/10626859/128768895-2374309b-65d9-4c7d-adaf-4ff42629c999.png)

**Comment by CaptainSaveACode** [comment]
Have you tried setting transforms through code?
This isn't doing anything:
```csharp
var transform = new PanelTransform
{
    List = System.Collections.Immutable.ImmutableList.Create( new PanelTransform.Entry
    {
        Type = PanelTransform.EntryType.Rotation, Data = Vector3.Random
    })
};
PanelRef.Style.Transform = transform;
```

**Comment by xezno** [comment]
Should be fixed on next update

**Comment by PolSpock** [comment]
Not sure, or this is a new unexpected behavior :

- HTML/CSS Code in web browser :

https://jsfiddle.net/xdsekn18/1/
![Image](https://github.com/user-attachments/assets/caf2445f-afa2-4197-81d1-1f0167e9175f)


- Ingame s&box rendering :
![Image](https://github.com/user-attachments/assets/156f2ccd-627b-40a4-a49d-6848bb52f1a5)

I need to change my rotation for my sub object to :
```
        .avatar {
            position: absolute;
            width: 182px;
            height: 182px;
            background-size: cover;
            transform: rotate(0.01deg);
        }

        svg {
            width: 64px;
            height: 64px;
            transform: rotate(0.01deg);
        }
```


In order to getting the same behavior as the web browser (was working well before):
![Image](https://github.com/user-attachments/assets/91fe7db9-d0e6-4fee-a8a6-4f9f157cbaaa)
