### ISSUE TITLE
Unable to load map when testing multiplayer

### ISSUE THREAD

**Issue by Remscar** [Facepunch/sbox-issues#6573]
### Describe the bug

When testing multiplayer in the editor with `Join via new instance` the map used in a scene cannot be loaded by the new instance.

The following error is in console:
`Couldn't load map (Unable to create world for map 'devtestmap')`

### To Reproduce

Here is a simple project that will reproduce the issue:

https://github.com/Remscar/sandbox-tester/tree/bug/network-test-map

### Expected behavior

The map should be sent to the new instance and opened successfully.

**Comment by badandbest** [comment]
Possibly related https://github.com/Facepunch/sbox-issues/issues/6569

**Comment by solwllms** [comment]
Heads up this is because your map was not compiled (Hammer: File > Build Map)

I've thrown in a more user friendly console message and added a warning hint to the inspector because it wasn't really clear at all why this wasn't working, so cheers for flagging this.

![](https://files.facepunch.com/solw/2024/October/09_19-20-JumpyOropendola.png)

**Comment by Remscar** [comment]
@solwllms The map is compiled, and even when I recompile it, it does this.

![Image](https://github.com/user-attachments/assets/9c393edb-10be-4823-a8c6-e77651c4d56b)

**Comment by solwllms** [comment]
You're right, I've just pushed a fix if you can give it a test on your end?

**Comment by Remscar** [comment]
> You're right, I've just pushed a fix if you can give it a test on your end?

Works like a charm! Thank you so much!
