### ISSUE TITLE
Add a quick play button in the main menu

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6576]
### What can't you do?

Currently, you have to load one main scene for a game. It could be a menu, could not be. In some cases, I think a menu is needed to give users more customization, like map selection, etc. Matt made a good point within the discord, saying he wants to jump into a game without having to go through a menu. That's why I think a quick-play option could be useful for games that want to have menus, but still allow players to jump right into the action.

### How would you like it to work?

I would like it to work as a scene you can set in your project settings. Like the map select scene. I would the quick play button to be accessible in two places. 

Here in this right-click menu:
![Image](https://github.com/user-attachments/assets/e2307932-ac4f-4480-9f49-1d4fb1972c5f)
And here in the game modal:
![Image](https://github.com/user-attachments/assets/806b6e8e-6f45-413b-bad1-2fb1da95b62d)

Pressing the button would load the quick play scene.

### What have you tried?

Doesn't apply to the issue.

**Comment by CarsonKompon** [comment]
I don't think we should be adding more launch options, it just makes things more confusing for players who don't know which option they should be choosing (Especially when every game's definition of "New Game" and "Quick Play" would be different)

It's also worth noting that the existing "Join Game" button already does what you're asking for. It wouldn't make sense for you to "Quick Play" into an empty lobby for a game like Fortwars because you still need a Main Menu to select the Map, GameRules, Time/Score Limits, ect for the server you're hosting. As-is, if a lobby exists, the "Join Game" button will directly connect you to the most populated lobby, skipping the Menu.

IMO, if you think your game warrants a Main Menu, create a Main Menu. Otherwise, don't create a Main Menu and let your game explain itself, then leave any customization/options in a Pause Menu.
