### ISSUE TITLE
Option to use relative paths for solutions and csproj files

### ISSUE THREAD

**Issue by LavenderTheGreat** [Facepunch/sbox-issues#677]
**What can't you do?**
When developing in multiple locations, or in environments where the games idea of the path may be different from the actual path used by editors (Proton, VMs and containers), the automatically set paths by S&box will cause a lot of linting and syntax checking errors.

**How would you like it to work?**
Relative paths instead of absolute paths. This'd also assist in the portability of code generated, allowing it to work in editors out of the box without having to boot the game.

**What have you tried?**
I have a script [here](https://gist.github.com/LavenderTheGreat/eec61aaff966dbceca6b3bbae08c2799) which resolves it but each time the game reboots, the script has to be rerun which is undesirable.

**Comment by Rohansi** [comment]
Not sure how possible this is. Relative paths would work fine if everything was in the s&box addons folder - but there could be addons in different paths or even different drives. The relative paths just wouldn't work out in that case because even the relative paths would be different.

I think the alternative here is you gitignore your sln and csproj files so they can be different but correct no matter what PC it's on. They're auto-generated files and they rarely actually change so why not?

**Comment by LavenderTheGreat** [comment]
They change every time the game boots as it regenerates them. Maybe an alternative would be to prevent paths being regenerated on a per addon basis.

**Comment by handsomematt** [comment]
This is implemented now.
