### ISSUE TITLE
`OnChildAdded` and `OnChildRemoved` fail to be called when overriding base inventory class

### ISSUE THREAD

**Issue by mzegar** [Facepunch/sbox-issues#705]
**What can't you do?**

I want to override `BaseInventory` and have a property on my `Player` class that replaces the original inventory property.

Here's an example...
```csharp
// Override the base inventory class
public partial class Inventory : BaseInventory

// TTTPlayer.cs
public partial class TTTPlayer : Sandbox.Player
{
	// Sandbox.Player has an `Inventory` property of type `BaseInventory`, I want to be able to "override"
	// this property with my new derived class.
	public new Inventory Inventory { get; }
	...
}
```

If you use the example above, we can use the [new](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier) keyword to hide the inherited member, but, this causes `OnChildAdded` and `OnChildRemoved` to fail to ever be called (I'm assuming they are event listeners setup somewhere, I don't have access to this code)

**How would you like it to work?**

Let me override the `Inventory` property, or make it such that if we use the `new` keyword `OnChildAdded` and `OnChildRemoved` works.

**What have you tried?**

I mentioned it above

**Additional context**

**Comment by Rohansi** [comment]
Why do you want to override `Inventory`? You should be able to set it to a different inventory implementation already (the setter is protected, not private/internal).

If you just want `TTTPlayer.Inventory` to have the type of your custom inventory you should be able to use:
```csharp
public new Inventory Inventory => base.Inventory;
```

FYI: `new` is a kind of terrible thing. By design the method/property marked as `new` will only be usable when through the type that declared it (in this case, `TTTPlayer`). If it is casted to a `Sandbox.Player` it will refer to the original method/property. That's just a standard C# thing.

**Comment by mzegar** [comment]
@Rohansi thanks, yeah that works.
