### ISSUE TITLE
Allow access to System.Threading.EventWaitHandle synchronization primitives

### ISSUE THREAD

**Issue by tuvangezer** [Facepunch/sbox-issues#917]
**What can't you do?**
Synchronize between tasks using the primitives designed to do that.

**How would you like it to work?**
Use EventWaitHandles instead of ugly and inefficient hacks.
```
System.Threading.EventWaitHandle
System.Threading.WaitHandle
System.Threading.EventResetMode
```

**What have you tried?**
```
while ( flag = false )
{
    await Task.Delay( 100 );
}
``` 
It works. But not putting a delay will eat so many CPU cycles and putting a delay essentially adds a latency to every event. 

**Additional context**
There might be a security concern with named events
https://docs.microsoft.com/en-us/dotnet/standard/threading/eventwaithandle#named-events

**Comment by Rohansi** [comment]
What do you need to synchronize? Right now all tasks should be running on the main thread so these don't actually make much sense right now.

If you're trying to wait for something asynchronous to complete then you might actually want a [TaskCompletionSource](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=net-5.0). This allows you to construct a `Task` which completes whenever you call `SetResult` on it.

If we were going to add synchronization primitives I think we'd add ones that are `async`-capable like `ManualResetEventSlim` and `SemaphoreSlim`. The problem is these classes kind of open things up where it'll be easy to shoot yourself in the foot with deadlocks.

**Comment by tuvangezer** [comment]
My use case that led to wanting this was a Websocket API wrapper but I can imagine other use cases.
pseudocode:
```
async SendMessageAndWaitAnswer(message) {
    websocket.send(message)
    eventhandler.wait()
    return answer
}
void OnMessageReceived(message) {
    if (something is waiting for this message) {
        answer = message
        eventhandler.set()
    }
}
```
My current working implementation is
```
async SendMessageAndWaitAnswer(message) {
    websocket.send(message)
    while (answer == "") { await Task.Delay(100) }
    return answer
}
void OnMessageReceived(message) {
    if (something is waiting for this message) {
        answer = message
        eventhandler.set()
    }
}
```

**Comment by Rohansi** [comment]
Cool, yeah this is something you should use TaskCompletionSource for.

```
async SendMessageAndWaitAnswer(message) {
    websocket.send(message)
    create new TaskCompletionSource (tcs) and save it somewhere
    return await tcs.Task
}
void OnMessageReceived(message) {
    if (find matching TaskCompletionSource (tcs) for this message) {
        tcs.SetResult(message)
    }
}
```

**Comment by tuvangezer** [comment]
Thanks! That solves my issue, I leave it up to you to close this issue if you believe EventWaitHandle is unnecessary.
