### ISSUE TITLE
Assets using color255 are being converted to use non-normalized color values (0-255)

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#928]
**Describe the bug**
Assets using color255 are being converted to use non-normalized color values (0-255)
This means assets that use these colors in C# will represent the wrong color

**To Reproduce**
- Make an asset that has a Color property, use AutoGen and let it generate the fgd.
- Print out the r g b values in C#
- Observe

**Expected behavior**
- Color values should be normalized

**Workaround**
- For now I'm just checking to see if my individual color values are above 1 and dividing by 255

**Screenshots**
![image](https://user-images.githubusercontent.com/22372616/133611973-08294d6d-0664-4e34-9d05-4698af94361a.png)
![image](https://user-images.githubusercontent.com/22372616/133612003-ad6a8d22-105a-43d2-8a9c-84625e1d9694.png)

**Comment by robotboy655** [comment]
Basically the issue is that for map colors are ultimately exported as a string of "255 255 255 255" while for assets it's an array of 3 elements for RGB.

The C# JSON converter for colors expects the array values in range 0-1 while the assets give it range of 0-255.

The way I see it there are 2 possible solutions:
1. Switch JSON converter to use range of 255 (like it should've been doing from the start IMO) which will break existing community assets/code.
2. Switch assets to export color255 as a string so it parses from JSON correctly, which can possibly break things in the engine.

**Comment by DevulTj** [comment]
I think breaking stuff for players is better than breaking stuff in engine. I have a workaround extension method that just fixes my color if any of the values are above 1 but many people will run into this issue.

**Comment by garrynewman** [comment]
There's a bit of a mess here with using byte values. I prefer to use floats because it gives you HDR for free. I don't really agree that json colours should expect 0-255, we have Color32 for that.

IMO what we should be doing where possible is converting from a Color32 in native to a Color before we pass it to c#. So we should really identify where that's happening and do it automatically where possible, and where not do it by hand.

**Comment by mzegar** [comment]
Hey, ran into this myself, is there any plans for a solution?

**Comment by robotboy655** [comment]
I have pushed some changes that should resolve the issue. It will require you to adjust your assets and recompile them.

It will now correctly work on 0..1 scale for assets.

**Comment by mzegar** [comment]
Works for me, if @DevulTj wants to test and close this thread.

Thanks!

**Comment by DevulTj** [comment]
I'll trust your judgement.
